'use client';

import {
  ActivityIcon,
  AlarmClockIcon,
  ArchiveIcon,
  AwardIcon,
  BellIcon,
  BookmarkIcon,
  BriefcaseIcon,
  BugIcon,
  CalendarIcon,
  CheckIcon,
  CircleAlertIcon,
  CircleCheckIcon,
  CircleDashedIcon,
  CircleDotIcon,
  CircleIcon,
  ClockIcon,
  CoffeeIcon,
  FileTextIcon,
  FlagIcon,
  FolderIcon,
  GiftIcon,
  HammerIcon,
  HeartIcon,
  HourglassIcon,
  InboxIcon,
  LayersIcon,
  LightbulbIcon,
  ListChecksIcon,
  ListIcon as ListGlyphIcon,
  ListTodoIcon,
  LockIcon,
  MailIcon,
  MessageSquareIcon,
  PackageIcon,
  PaperclipIcon,
  PauseIcon,
  PinIcon,
  PlayIcon,
  RocketIcon,
  SparklesIcon,
  SquareCheckIcon,
  StarIcon,
  TagIcon,
  TargetIcon,
  ThumbsUpIcon,
  TimerIcon,
  TrendingUpIcon,
  TriangleAlertIcon,
  TrophyIcon,
  UserIcon,
  UsersIcon,
  WrenchIcon,
  ZapIcon,
  type LucideIcon,
} from 'lucide-react';
import { LIST_ICON_COLORS, LIST_ICONS, type ListIcon, type ListIconColor } from '@pusula/domain';

const LIST_ICON_SET = new Set<string>(LIST_ICONS);
const LIST_ICON_COLOR_SET = new Set<string>(LIST_ICON_COLORS);

export const LIST_ICON_COMPONENTS: Record<ListIcon, LucideIcon> = {
  circle: CircleIcon,
  'circle-dot': CircleDotIcon,
  'circle-dashed': CircleDashedIcon,
  'circle-check': CircleCheckIcon,
  'circle-alert': CircleAlertIcon,
  check: CheckIcon,
  'square-check': SquareCheckIcon,
  list: ListGlyphIcon,
  'list-todo': ListTodoIcon,
  'list-checks': ListChecksIcon,
  layers: LayersIcon,
  play: PlayIcon,
  pause: PauseIcon,
  hourglass: HourglassIcon,
  timer: TimerIcon,
  'alarm-clock': AlarmClockIcon,
  star: StarIcon,
  flag: FlagIcon,
  bookmark: BookmarkIcon,
  tag: TagIcon,
  pin: PinIcon,
  sparkles: SparklesIcon,
  lightbulb: LightbulbIcon,
  heart: HeartIcon,
  'thumbs-up': ThumbsUpIcon,
  clock: ClockIcon,
  calendar: CalendarIcon,
  user: UserIcon,
  users: UsersIcon,
  bell: BellIcon,
  'message-square': MessageSquareIcon,
  mail: MailIcon,
  briefcase: BriefcaseIcon,
  target: TargetIcon,
  rocket: RocketIcon,
  zap: ZapIcon,
  trophy: TrophyIcon,
  award: AwardIcon,
  'trending-up': TrendingUpIcon,
  activity: ActivityIcon,
  folder: FolderIcon,
  'file-text': FileTextIcon,
  paperclip: PaperclipIcon,
  inbox: InboxIcon,
  archive: ArchiveIcon,
  package: PackageIcon,
  'triangle-alert': TriangleAlertIcon,
  lock: LockIcon,
  bug: BugIcon,
  wrench: WrenchIcon,
  hammer: HammerIcon,
  gift: GiftIcon,
  coffee: CoffeeIcon,
};

export const LIST_ICON_FG: Record<ListIconColor, string> = {
  kirmizi: 'text-palet-kirmizi',
  turuncu: 'text-palet-turuncu',
  sari: 'text-palet-sari',
  lime: 'text-palet-lime',
  yesil: 'text-palet-yesil',
  sky: 'text-palet-sky',
  mavi: 'text-palet-mavi',
  indigo: 'text-palet-indigo',
  mor: 'text-palet-mor',
  pembe: 'text-palet-pembe',
  gri: 'text-palet-gri',
  siyah: 'text-palet-siyah',
};

export const LIST_ICON_SWATCH_BG: Record<ListIconColor, string> = {
  kirmizi: 'bg-palet-kirmizi',
  turuncu: 'bg-palet-turuncu',
  sari: 'bg-palet-sari',
  lime: 'bg-palet-lime',
  yesil: 'bg-palet-yesil',
  sky: 'bg-palet-sky',
  mavi: 'bg-palet-mavi',
  indigo: 'bg-palet-indigo',
  mor: 'bg-palet-mor',
  pembe: 'bg-palet-pembe',
  gri: 'bg-palet-gri',
  siyah: 'bg-palet-siyah',
};

export const LIST_ICON_CHECK_FG: Record<ListIconColor, string> = {
  kirmizi: 'text-palet-kirmizi-foreground',
  turuncu: 'text-palet-turuncu-foreground',
  sari: 'text-palet-sari-foreground',
  lime: 'text-palet-lime-foreground',
  yesil: 'text-palet-yesil-foreground',
  sky: 'text-palet-sky-foreground',
  mavi: 'text-palet-mavi-foreground',
  indigo: 'text-palet-indigo-foreground',
  mor: 'text-palet-mor-foreground',
  pembe: 'text-palet-pembe-foreground',
  gri: 'text-palet-gri-foreground',
  siyah: 'text-palet-siyah-foreground',
};

export function asListIcon(icon: string | null): ListIcon | null {
  return icon != null && LIST_ICON_SET.has(icon) ? (icon as ListIcon) : null;
}

export function asListIconColor(color: string | null): ListIconColor | null {
  return color != null && LIST_ICON_COLOR_SET.has(color) ? (color as ListIconColor) : null;
}
