/**
 * User-facing copy for the web app, centralized in one place. This is a
 * placeholder for a real i18n layer (next-intl, etc.) — until then, components
 * read strings from here instead of inlining literals, so the eventual swap is a
 * single seam. Keep keys grouped by feature; values are plain Turkish strings.
 */

/** Display labels for workspace roles, used in badges and the role <Select>. */
export const workspaceRoleLabels = {
  owner: 'Sahip',
  admin: 'Yönetici',
  member: 'Üye',
  guest: 'Misafir',
} as const;

/** Display labels for board roles, used in badges. */
export const boardRoleLabels = {
  admin: 'Yönetici',
  member: 'Üye',
  viewer: 'İzleyici',
} as const;

export const strings = {
  common: {
    appName: 'Pusula',
    loading: 'Yükleniyor…',
    cancel: 'İptal',
    retry: 'Tekrar dene',
    back: 'Geri',
    unknownError: 'Beklenmeyen bir hata oluştu. Lütfen tekrar deneyin.',
  },
  auth: {
    emailLabel: 'E-posta',
    emailPlaceholder: 'ornek@eposta.com',
    passwordLabel: 'Parola',
    passwordPlaceholder: '••••••••',
    nameLabel: 'Ad',
    namePlaceholder: 'Adınız',
    signIn: {
      title: 'Giriş yap',
      description: 'Hesabınızla devam edin.',
      submit: 'Giriş yap',
      submitting: 'Giriş yapılıyor…',
      noAccount: 'Hesabın yok mu?',
      goToSignUp: 'Kayıt ol',
    },
    signUp: {
      title: 'Kayıt ol',
      description: 'Yeni bir hesap oluşturun.',
      submit: 'Kayıt ol',
      submitting: 'Kayıt olunuyor…',
      hasAccount: 'Zaten hesabın var mı?',
      goToSignIn: 'Giriş yap',
    },
  },
  shell: {
    signOut: 'Çıkış',
    signingOut: 'Çıkış yapılıyor…',
  },
  workspace: {
    listTitle: 'Workspace’lerin',
    loading: 'Workspace’ler yükleniyor…',
    loadErrorTitle: 'Workspace’ler yüklenemedi',
    redirecting: 'Workspace’ine yönlendiriliyorsun…',
    newButton: 'Yeni workspace',
    roleBadgePrefix: 'Rol:',
    openManage: 'Workspace’i aç',
    create: {
      title: 'Yeni workspace',
      description: 'Bir ad verin; sahibi siz olursunuz.',
      nameLabel: 'Workspace adı',
      namePlaceholder: 'Örn. Pazarlama Ekibi',
      submit: 'Oluştur',
      submitting: 'Oluşturuluyor…',
    },
    manage: {
      backToList: 'Workspace’lere dön',
      loading: 'Workspace yükleniyor…',
      loadErrorTitle: 'Workspace yüklenemedi',
      memberCount: 'üye',
      settingsTitle: 'Workspace ayarları',
      settingsDescription: 'Workspace adını ve adresini (slug) güncelleyin.',
      nameLabel: 'Workspace adı',
      namePlaceholder: 'Örn. Pazarlama Ekibi',
      slugLabel: 'Adres (slug)',
      slugPlaceholder: 'orn-pazarlama-ekibi',
      slugHelp: 'Yalnızca küçük harf, rakam ve tire.',
      save: 'Kaydet',
      saving: 'Kaydediliyor…',
      saved: 'Değişiklikler kaydedildi.',
      noChange: 'Değişiklik yok.',
      dangerTitle: 'Tehlikeli bölge',
      dangerDescription: 'Workspace’i arşivlemek listeden kaldırır; içerik silinmez.',
      archiveButton: 'Workspace’i arşivle',
      archiving: 'Arşivleniyor…',
      archiveConfirmTitle: 'Workspace arşivlensin mi?',
      archiveConfirmDescription:
        'Bu workspace listenizden kaldırılır. İçerik silinmez; ileride bir yöneticinin geri alması gerekir.',
      archiveConfirm: 'Arşivle',
      deleteAction: 'Workspace’i kalıcı sil',
      deleteDialogTitle: 'Workspace’i kalıcı sil',
      deleteDialogDescription:
        'Bu işlem geri alınamaz. Workspace ve tüm üyeleri, davetleri, panoları kalıcı olarak silinir.',
      deleteConfirmNameLabel: 'Workspace adı',
      deleteConfirmNamePrompt: 'Onaylamak için workspace adını yazın:',
      deleteConfirm: 'Kalıcı sil',
      deleting: 'Siliniyor…',
    },
  },
  members: {
    sectionTitle: 'Üyeler',
    sectionDescription: 'Workspace üyelerini görüntüleyin; rollerini değiştirin veya çıkarın.',
    loading: 'Üyeler yükleniyor…',
    loadErrorTitle: 'Üyeler yüklenemedi',
    empty: 'Üye yok.',
    roleLabel: 'Rol',
    youBadge: 'Bu sizsiniz',
    ownerBadge: 'Sahip',
    remove: 'Çıkar',
    removing: 'Çıkarılıyor…',
    removeConfirmTitle: 'Üye çıkarılsın mı?',
    removeConfirmDescription:
      'Bu kişi workspace’ten çıkarılacak. Tekrar erişmesi için yeniden davet edilmesi gerekir.',
    removeConfirm: 'Çıkar',
    leave: 'Workspace’ten ayrıl',
    leaving: 'Ayrılınıyor…',
    leaveConfirmTitle: 'Workspace’ten ayrılınsın mı?',
    leaveConfirmDescription:
      'Bu workspace’e erişiminizi kaybedersiniz. Tekrar erişmek için yeniden davet edilmeniz gerekir.',
    leaveConfirm: 'Ayrıl',
  },
  board: {
    listSectionTitle: 'Panolar',
    listSectionDescription: 'Bu workspace’teki panolar.',
    loading: 'Panolar yükleniyor…',
    loadErrorTitle: 'Panolar yüklenemedi',
    empty: 'Henüz pano yok — ilkini oluştur.',
    archivedBadge: 'Arşivli',
    newButton: 'Pano oluştur',
    roleBadgePrefix: 'Rol:',
    create: {
      title: 'Yeni pano',
      description: 'Bir ad verin; bu panonun yöneticisi siz olursunuz.',
      nameLabel: 'Pano adı',
      namePlaceholder: 'Örn. Ürün Yol Haritası',
      submit: 'Oluştur',
      submitting: 'Oluşturuluyor…',
    },
    detail: {
      backToWorkspace: 'Workspace’e dön',
      loading: 'Pano yükleniyor…',
      loadErrorTitle: 'Pano yüklenemedi',
      archivedNote: 'Bu pano arşivli — salt okunur.',
      rename: 'Pano adını değiştir',
      renamePlaceholder: 'Pano adı',
      renameSave: 'Kaydet',
      renameSaving: 'Kaydediliyor…',
      renameCancel: 'Vazgeç',
      archive: 'Panoyu arşivle',
      archiving: 'Arşivleniyor…',
      archiveConfirmTitle: 'Pano arşivlensin mi?',
      archiveConfirmDescription:
        'Bu pano arşivlenir ve salt okunur olur. İçerik silinmez; bir yönetici geri alabilir.',
      archiveConfirm: 'Arşivle',
      restore: 'Panoyu geri yükle',
      restoring: 'Geri yükleniyor…',
      emptyBoard: 'Bu panoda henüz liste yok.',
    },
    column: {
      addList: 'Liste ekle',
      addListPlaceholder: 'Liste adı',
      addListSubmit: 'Ekle',
      addListSubmitting: 'Ekleniyor…',
      renamePlaceholder: 'Liste adı',
      renameSave: 'Kaydet',
      renameSaving: 'Kaydediliyor…',
      archive: 'Listeyi arşivle',
      archiving: 'Arşivleniyor…',
      archiveConfirmTitle: 'Liste arşivlensin mi?',
      archiveConfirmDescription:
        'Bu liste arşivlenir. İçindeki kartlar korunur; bir üye listeyi geri alabilir.',
      archiveConfirm: 'Arşivle',
      restore: 'Listeyi geri yükle',
      restoring: 'Geri yükleniyor…',
      archivedLabel: 'Arşivli',
      empty: 'Bu listede kart yok.',
    },
    card: {
      addCard: 'Kart ekle',
      addCardPlaceholder: 'Kart için bir başlık girin…',
      addCardSubmit: 'Ekle',
      addCardSubmitting: 'Ekleniyor…',
      addCardCancel: 'Vazgeç',
      edit: 'Kartı düzenle',
      archive: 'Kartı arşivle',
      archiving: 'Arşivleniyor…',
      archiveConfirmTitle: 'Kart arşivlensin mi?',
      archiveConfirmDescription: 'Bu kart arşivlenir ve panodan kaldırılır.',
      archiveConfirm: 'Arşivle',
      dueLabel: 'Son tarih',
      editDialogTitle: 'Kartı düzenle',
      editDialogReadonlyTitle: 'Kart',
      titleLabel: 'Başlık',
      titlePlaceholder: 'Kart başlığı',
      descriptionLabel: 'Açıklama',
      descriptionPlaceholder: 'Bu kart hakkında notlar…',
      dueAtLabel: 'Son tarih',
      noDescription: 'Açıklama yok.',
      noDueAt: 'Son tarih yok.',
      save: 'Kaydet',
      saving: 'Kaydediliyor…',
      noChange: 'Değişiklik yok.',
      close: 'Kapat',
    },
  },
  invitations: {
    inviteAction: 'Üye davet et',
    inviteDialogTitle: 'Workspace’e üye davet et',
    inviteDialogDescription: 'Davet edilen kişiye e-posta ile davet bağlantısı gönderilir.',
    inviteEmailLabel: 'E-posta',
    inviteEmailPlaceholder: 'ornek@eposta.com',
    inviteSubmit: 'Davet gönder',
    inviteSubmitting: 'Gönderiliyor…',
    pendingTitle: 'Bekleyen davetler',
    accept: 'Kabul et',
    accepting: 'Kabul ediliyor…',
    decline: 'Reddet',
    declining: 'Reddediliyor…',
    invitedBy: 'Davet eden',
    expiresAt: 'Son tarih',
    sentTitle: 'Gönderilmiş davetler',
    sentDescription: 'Bu workspace’e gönderilen ve henüz yanıtlanmamış davetler.',
    loadErrorTitle: 'Davetler yüklenemedi',
    noSent: 'Bekleyen davet yok.',
    revoke: 'İptal et',
    revoking: 'İptal ediliyor…',
    revokeConfirmTitle: 'Davet iptal edilsin mi?',
    revokeConfirmDescription:
      'Bu davet geçersiz hale gelir. Kişi davet bağlantısını artık kullanamaz.',
    revokeConfirm: 'Daveti iptal et',
  },
  onboarding: {
    title: 'Pusula’ya hoş geldin',
    intro:
      'Çalışma alanların (workspace) ekiplerini ve panolarını gruplar; her panoda listeler ve kartlarla işleri takip edersin. Başlamak için ilk çalışma alanını oluştur.',
    hint: 'Otomatik bir çalışma alanı oluşturulamadı. Aşağıdan kendin oluşturabilirsin.',
    createCta: 'İlk çalışma alanını oluştur',
  },
} as const;
