/**
 * User-facing copy for the web app, centralized in one place. This is a
 * placeholder for a real i18n layer (next-intl, etc.) — until then, components
 * read strings from here instead of inlining literals, so the eventual swap is a
 * single seam. Keep keys grouped by feature; values are plain Turkish strings.
 */

/** Display labels for workspace roles, used in badges and the role <Select>. */
export const workspaceRoleLabels = {
  owner: 'Sahip',
  admin: 'Yönetici',
  member: 'Üye',
  guest: 'Misafir',
} as const;

/** Display labels for board roles, used in badges. */
export const boardRoleLabels = {
  admin: 'Yönetici',
  member: 'Üye',
  viewer: 'İzleyici',
} as const;

/** Display labels for card-member roles (`assignee` / `watcher`). */
export const cardRoleLabels = {
  assignee: 'Sorumlu',
  watcher: 'İzleyen',
} as const;

export const strings = {
  common: {
    appName: 'Pusula',
    loading: 'Yükleniyor…',
    cancel: 'İptal',
    close: 'Kapat',
    retry: 'Tekrar dene',
    back: 'Geri',
    unknownError: 'Beklenmeyen bir hata oluştu. Lütfen tekrar deneyin.',
  },
  entityIcons: {
    'layout-grid': 'Izgara',
    'layout-dashboard': 'Pano düzeni',
    'layout-list': 'Liste düzeni',
    briefcase: 'Çanta',
    folder: 'Klasör',
    'folder-open': 'Açık klasör',
    building: 'Bina',
    factory: 'Fabrika',
    store: 'Mağaza',
    home: 'Ev',
    archive: 'Arşiv',
    inbox: 'Gelen kutusu',
    package: 'Paket',
    boxes: 'Kutular',
    users: 'Ekip',
    user: 'Kullanıcı',
    network: 'Ağ',
    target: 'Hedef',
    rocket: 'Roket',
    flag: 'Bayrak',
    trophy: 'Kupa',
    award: 'Ödül',
    crown: 'Taç',
    gem: 'Mücevher',
    zap: 'Hızlı',
    'trending-up': 'Yükseliş',
    star: 'Yıldız',
    bookmark: 'Yer imi',
    heart: 'Kalp',
    sparkles: 'Parıltı',
    lightbulb: 'Fikir',
    calendar: 'Takvim',
    clock: 'Saat',
    map: 'Harita',
    compass: 'Pusula',
    globe: 'Küre',
    'book-open': 'Kitap',
    'clipboard-list': 'Pano listesi',
    'graduation-cap': 'Mezuniyet',
    puzzle: 'Yapboz',
    code: 'Kod',
    terminal: 'Terminal',
    database: 'Veritabanı',
    server: 'Sunucu',
    palette: 'Palet',
    camera: 'Kamera',
    music: 'Müzik',
    leaf: 'Yaprak',
    sun: 'Güneş',
    shield: 'Kalkan',
    bell: 'Zil',
    megaphone: 'Anons',
    'shopping-cart': 'Sepet',
  },
  realtime: {
    // Subtle banner shown on the board page while the Socket.IO link is down
    // (Phase 5C — DEM-85). Reconnect is automatic.
    disconnected: 'Bağlantı koptu, tekrar bağlanılıyor…',
  },
  auth: {
    emailLabel: 'E-posta',
    emailPlaceholder: 'ornek@eposta.com',
    passwordLabel: 'Parola',
    passwordPlaceholder: '••••••••',
    nameLabel: 'Ad',
    namePlaceholder: 'Adınız',
    brandPanel: {
      eyebrow: 'Pusula · Görev ve Pano Yönetimi',
      headline: {
        prefix: 'Ekibinizin işlerini',
        emphasis: 'tek yönde',
        suffix: 'toplayın.',
      },
      description:
        'Workspace, pano ve kart akışlarını tek ekranda yönetin. Yetki, takip ve bildirimler her ekip için açık, hızlı ve tutarlı kalsın.',
      advantages: [
        'Workspace bazlı yetki ve ekip düzeni',
        'Mobil uyumlu kanban panoları',
        'Bildirimler ve aktivite geçmişiyle görünür takip',
      ],
      footer: 'Pusula ekiplerin plan, takip ve karar akışını aynı yerde toplar.',
      summary: {
        label: 'Aktif Pano',
        title: 'Ürün Yol Haritası',
        status: 'Devam ediyor',
        metrics: [
          { title: 'Açık kart', value: '24' },
          { title: 'Bu hafta', value: '7' },
          { title: 'Ekip', value: '12' },
        ],
      },
    },
    signIn: {
      title: 'Tekrar hoş geldiniz',
      description: 'Hesabınızla giriş yapın ve panolarınıza kaldığınız yerden devam edin.',
      submit: 'Giriş yap',
      submitting: 'Giriş yapılıyor…',
      noAccount: 'Hesabınız yok mu?',
      goToSignUp: 'Kayıt ol',
      forgotPassword: 'Unuttum',
      resetDone: 'Parolan güncellendi. Yeni parolanla giriş yapabilirsin.',
    },
    signUp: {
      title: 'Hesap oluşturun',
      description: 'Yeni bir Pusula hesabı oluşturun ve ekip panolarınızı yönetmeye başlayın.',
      submit: 'Kayıt ol',
      submitting: 'Kayıt olunuyor…',
      hasAccount: 'Zaten hesabınız var mı?',
      goToSignIn: 'Giriş yap',
    },
    forgotPassword: {
      title: 'Şifreni mi unuttun?',
      description: 'E-posta adresini gir; sana bir sıfırlama bağlantısı gönderelim.',
      submit: 'Sıfırlama bağlantısı gönder',
      submitting: 'Gönderiliyor…',
      successTitle: 'Bağlantı yolda',
      // E-posta adresi araya konur — hesap kayıtlı mı belli edilmez (kullanıcı
      // listesi sızdırılmaz); kayıt yoksa Better Auth da sessizce başarı döner.
      successBodyPrefix: 'Eğer ',
      successBodySuffix:
        ' adresine bağlı bir hesap varsa, bir parola sıfırlama bağlantısı gönderdik. Gelen kutunu (ve spam klasörünü) kontrol et.',
      resend: 'Yeniden gönder',
      backToSignIn: 'Giriş ekranına dön',
    },
    resetPassword: {
      title: 'Yeni parola belirle',
      description: 'Hesabın için yeni bir parola gir.',
      newPasswordLabel: 'Yeni parola',
      confirmPasswordLabel: 'Yeni parola (tekrar)',
      passwordPlaceholder: '••••••••',
      passwordMismatch: 'Parolalar eşleşmiyor.',
      submit: 'Parolayı güncelle',
      submitting: 'Güncelleniyor…',
      successTitle: 'Parolan güncellendi',
      redirecting: 'Giriş ekranına yönlendiriliyorsun…',
      missingTokenTitle: 'Bağlantı geçersiz veya eksik',
      missingTokenBody:
        'Bu sıfırlama bağlantısı eksik ya da bozuk görünüyor. Yeni bir bağlantı isteyebilirsin.',
      requestNewLink: 'Yeni bağlantı iste',
      backToSignIn: 'Giriş ekranına dön',
    },
    verifyEmail: {
      bannerTitle: 'E-postanı doğrula',
      bannerBody: 'Hesabını güvende tutmak için e-posta adresini doğrula.',
      resend: 'Doğrulama e-postasını yeniden gönder',
      sending: 'Gönderiliyor…',
      sent: 'Doğrulama e-postası yeniden gönderildi. Gelen kutunu kontrol et.',
      error: 'Doğrulama e-postası gönderilemedi. Lütfen tekrar deneyin.',
      cooldownLabel: (seconds: number) => `Tekrar gönder (${seconds}sn)`,
      successTitle: 'E-posta doğrulandı',
      successBody: 'E-posta adresin doğrulandı. Pusula kullanmaya devam edebilirsin.',
      pendingTitle: 'E-posta doğrulanıyor',
      pendingBody: 'Doğrulama bağlantısı kontrol ediliyor…',
      invalidTitle: 'Doğrulama bağlantısı geçersiz',
      invalidBody:
        'Bu doğrulama bağlantısı geçersiz ya da süresi dolmuş. Uygulamaya girip yeni bir bağlantı isteyebilirsin.',
      goToApp: 'Uygulamaya git',
      goToSignIn: 'Giriş ekranına dön',
    },
  },
  shell: {
    signOut: 'Çıkış',
    signingOut: 'Çıkış yapılıyor…',
    accountSettings: 'Hesap ayarları',
    themeToggleToLight: 'Açık temaya geç',
    themeToggleToDark: 'Koyu temaya geç',
    fontSize: {
      trigger: 'Yazı boyutu',
      label: 'Yazı boyutu',
      decrease: 'Küçült',
      increase: 'Büyüt',
      reset: 'Sıfırla',
    },
    workspaceSwitcher: {
      heading: "Workspace'ler",
      placeholder: 'Workspace seç',
      empty: 'Henüz workspace yok',
      create: 'Workspace oluştur',
      manageAll: "Tüm workspace'leri yönet",
      ariaLabel: 'Workspace değiştir',
      rowSettings: 'Ayarlar',
      rowSettingsFor: (name: string) => `${name} ayarları`,
      rowMembers: 'Üyeler',
      rowMembersFor: (name: string) => `${name} üyeleri`,
    },
    boardSwitcher: {
      heading: 'Panolar',
      placeholder: 'Pano seç',
      disabled: 'Workspace seçin',
      disabledTooltip: 'Önce bir workspace seçin',
      empty: 'Henüz pano yok',
      create: 'Pano oluştur',
      manageWorkspace: "Workspace'i yönet",
      ariaLabel: 'Pano değiştir',
      rowSettings: 'Ayarlar',
      rowSettingsFor: (title: string) => `${title} ayarları`,
      rowMembers: 'Üyeler',
      rowMembersFor: (title: string) => `${title} üyeleri`,
    },
    userMenu: {
      account: 'Hesap ayarları',
      ariaLabel: 'Kullanıcı menüsü',
    },
    notifications: {
      label: 'Bildirimler',
      soon: 'Yakında',
    },
  },
  search: {
    globalTrigger: 'Ara',
    boardTrigger: 'Bu panoda ara',
    dialogTitle: 'Arama',
    boardDialogTitle: 'Pano araması',
    dialogDescription: 'Erişebildiğiniz pano, liste, kart, yorum ve etiket sonuçları.',
    inputLabel: 'Arama sorgusu',
    inputPlaceholder: 'Ara',
    minLength: 'En az 2 karakter yazın.',
    loading: 'Aranıyor…',
    empty: 'Sonuç yok.',
    errorTitle: 'Arama tamamlanamadı',
    entityTypes: {
      board: 'Panolar',
      list: 'Listeler',
      card: 'Kartlar',
      comment: 'Yorumlar',
      attachment: 'Dosyalar',
      label: 'Etiketler',
    },
  },
  shortcuts: {
    dialogTitle: 'Klavye kısayolları',
    dialogDescription: 'Pano ve kart ayrıntısı ekranlarında kullanılabilen kısayollar.',
    groups: {
      general: 'Genel',
      board: 'Pano',
      cardModal: 'Kart ayrıntısı',
    },
    keys: {
      commandK: 'Cmd/Ctrl+K',
      ctrlSpace: 'Ctrl+Space',
      slash: '/',
      question: '?',
      n: 'N',
      shiftN: 'Shift+N',
      l: 'L',
      e: 'E',
      c: 'C',
      d: 'D',
      m: 'M',
      t: 'T',
      a: 'A',
      escape: 'Esc',
    },
    actions: {
      globalSearch: 'Genel aramayı aç',
      boardSearch: 'Bu panoda ara',
      help: 'Kısayol yardımını aç',
      newCard: 'İlk aktif listeye kart ekle',
      newList: 'Liste ekle',
      editTitle: 'Kart başlığını düzenle',
      toggleComplete: 'Kart tamamlandı durumunu değiştir',
      dueDate: 'Son tarih alanını aç',
      members: 'Üyeler alanını aç',
      labels: 'Etiketler alanını aç',
      archive: 'Kartı arşivle veya geri yükle',
      closeModal: 'Kart penceresini kapat',
    },
  },
  notifications: {
    bellAria: (count: number) => (count === 0 ? 'Bildirimler' : `${count} okunmamış bildirim`),
    title: 'Bildirimler',
    markAllRead: 'Tümünü okundu işaretle',
    markOneRead: 'Okundu işaretle',
    openSettings: 'Bildirim ayarları',
    unreadDotLabel: 'Okunmamış',
    empty: 'Henüz bildirim yok',
    emptyHint: 'Sana yönelik aktiviteler burada görünecek.',
    loadErrorTitle: 'Bildirimler yüklenemedi',
    loadErrorHint: 'Bağlantını kontrol edip tekrar dene.',
    loadMore: 'Daha fazla yükle',
    unreadCountLabel: (count: number) => `${count} okunmamış`,
    allCaughtUp: 'Hepsi okundu',
    groups: {
      today: 'Bugün',
      yesterday: 'Dün',
      thisWeek: 'Bu hafta',
      earlier: 'Daha eski',
    },
    fallbackActorName: 'Bir kullanıcı',
    fallbackCardTitle: 'bu kart',
    fallbackBoardName: 'bu pano',
    fallbackWorkspaceName: 'bu çalışma alanı',
    summary: {
      cardMemberAdded: (cardTitle: string) => `sana "${cardTitle}" kartını atadı`,
      commentMentioned: (cardTitle: string) =>
        `"${cardTitle}" kartındaki bir yorumda senden bahsetti`,
      commentCreated: (cardTitle: string) => `"${cardTitle}" kartında yorum bıraktı`,
      dueApproaching: (cardTitle: string) => `"${cardTitle}" kartının teslim tarihi yaklaşıyor`,
      dueReminder1d: (cardTitle: string) => `"${cardTitle}" kartı yarın teslim ediliyor`,
      dueReminder1h: (cardTitle: string) => `"${cardTitle}" kartı 1 saat sonra teslim ediliyor`,
      dueOverdue: (cardTitle: string) => `"${cardTitle}" kartının teslim tarihi geçti`,
      boardMemberInvited: (boardName: string) => `seni "${boardName}" panosuna davet etti`,
      boardMemberAdded: (boardName: string) => `seni "${boardName}" panosuna ekledi`,
      workspaceMemberInvited: (workspaceName: string) =>
        `seni "${workspaceName}" çalışma alanına davet etti`,
      // DEM-154 — board erişim talebi bildirimi özeti (alıcı board admin'i).
      boardAccessRequested: (boardName: string) => `"${boardName}" panosuna erişim istedi`,
      watchedActivity: (cardTitle: string) => `"${cardTitle}" kartında değişiklik yaptı`,
      checklistItemCompleted: (cardTitle: string) =>
        `"${cardTitle}" kartındaki bir maddeyi tamamladı`,
      cardArchived: (cardTitle: string) => `"${cardTitle}" kartını arşivledi`,
      cardCompleted: (cardTitle: string) => `"${cardTitle}" kartını tamamlandı işaretledi`,
      // DEM-152 — granular kart-aktivite özetleri.
      cardMoved: (cardTitle: string) => `"${cardTitle}" kartını taşıdı`,
      cardUncompleted: (cardTitle: string) =>
        `"${cardTitle}" kartının tamamlandı işaretini kaldırdı`,
      cardDueSet: (cardTitle: string) => `"${cardTitle}" kartı için teslim tarihi belirledi`,
      cardDueCleared: (cardTitle: string) => `"${cardTitle}" kartının teslim tarihini kaldırdı`,
      cardCoverChanged: (cardTitle: string) => `"${cardTitle}" kartının kapağını değiştirdi`,
      cardMemberRemoved: (cardTitle: string) => `seni "${cardTitle}" kartından çıkardı`,
      attachmentAdded: (cardTitle: string) => `"${cardTitle}" kartına bir dosya ekledi`,
      // DEM-153 — kartla ilgili kalan granular aksiyon özetleri.
      cardRenamed: (cardTitle: string) => `"${cardTitle}" kartının başlığını değiştirdi`,
      cardDescriptionChanged: (cardTitle: string) =>
        `"${cardTitle}" kartının açıklamasını güncelledi`,
      cardLabelAdded: (cardTitle: string) => `"${cardTitle}" kartına bir etiket ekledi`,
      cardLabelRemoved: (cardTitle: string) => `"${cardTitle}" kartından bir etiket kaldırdı`,
      commentUpdated: (cardTitle: string) => `"${cardTitle}" kartındaki bir yorumu düzenledi`,
      commentDeleted: (cardTitle: string) => `"${cardTitle}" kartındaki bir yorumu sildi`,
      checklistCreated: (cardTitle: string) =>
        `"${cardTitle}" kartına bir yapılacaklar listesi ekledi`,
      checklistItemAdded: (cardTitle: string) =>
        `"${cardTitle}" kartına bir yapılacaklar maddesi ekledi`,
      checklistItemRemoved: (cardTitle: string) =>
        `"${cardTitle}" kartından bir yapılacaklar maddesi sildi`,
      attachmentRemoved: (cardTitle: string) => `"${cardTitle}" kartından bir dosya kaldırdı`,
      default: 'bir işlem yaptı',
    },
  },
  /**
   * Copy for the `(app)` landing page — the workspace-overview layout
   * (DEM-192 "Anasayfa Variant A"): the workspace rail, the selected
   * workspace's header, its stat strip and its board grid.
   */
  home: {
    rail: {
      eyebrow: 'Workspaces',
      count: (count: number) => `${count} çalışma alanı`,
      addLabel: 'Yeni çalışma alanı ekle',
      settingsLabel: (name: string) => `${name} ayarları`,
      createCardTitle: 'Yeni alan kur',
      createCardDescription: 'Ekibinle ayrı bir çalışma alanı başlat, üyeleri davet et.',
    },
    overview: {
      roleBadgePrefix: 'Rol ·',
      boardCount: (count: number) => `${count} pano`,
      memberCount: (count: number) => `${count} üye`,
      lastActivity: (relative: string) => `Son aktivite ${relative}`,
      lastActivityNever: 'Henüz aktivite yok',
      createBoardButton: 'Pano oluştur',
    },
    stats: {
      sectionLabel: 'Çalışma alanı özeti',
      loadErrorTitle: 'Özet yüklenemedi',
      openTasks: {
        label: 'Açık görev',
        sub: 'Bu çalışma alanında',
      },
      completedThisWeek: {
        label: 'Bu hafta tamamlanan',
        deltaUp: (count: number) => `Geçen haftaya göre +${count}`,
        deltaDown: (count: number) => `Geçen haftaya göre −${count}`,
        deltaSame: 'Geçen haftayla aynı',
      },
      overdue: {
        label: 'Vadesi geçen',
        sub: 'Hassasiyet ister',
        subEmpty: 'Geciken görev yok',
      },
      assignedToMe: {
        label: 'Bana atanan',
        sub: (count: number) =>
          count === 0 ? 'Bugün vadeli görevin yok' : `Bugün ${count} görev vadeli`,
      },
    },
    boards: {
      sectionTitle: 'Panolar',
      count: (count: number) => `· ${count}`,
      filterAll: 'Tümü',
      filterStarred: 'Yıldızlı',
      filterRecent: 'Son düzenlenen',
      viewGridLabel: 'Izgara görünümü',
      viewListLabel: 'Liste görünümü',
      empty: 'Henüz pano yok — ilkini oluştur.',
      emptyStarred: 'Yıldızlı pano yok.',
      newCardTitle: 'Yeni pano',
      newCardDescription: 'Şablonlardan başla veya boş aç.',
      taskCounts: (open: number, done: number) => `${open} açık / ${done} bitti`,
      memberOverflow: (count: number) => `+${count}`,
      memberStackLabel: (count: number) => `${count} üye`,
      favoriteAdd: (title: string) => `"${title}" panosunu yıldızla`,
      favoriteRemove: (title: string) => `"${title}" panosunun yıldızını kaldır`,
    },
  },
  workspace: {
    loading: 'Workspace’ler yükleniyor…',
    loadErrorTitle: 'Workspace’ler yüklenemedi',
    redirecting: 'Workspace’ine yönlendiriliyorsun…',
    newButton: 'Yeni workspace',
    roleBadgePrefix: 'Rol:',
    openManage: 'Workspace’i aç',
    create: {
      iconLabel: 'İkon',
      title: 'Yeni workspace',
      description: 'Bir ad verin; sahibi siz olursunuz.',
      nameLabel: 'Workspace adı',
      namePlaceholder: 'Örn. Pazarlama Ekibi',
      submit: 'Oluştur',
      submitting: 'Oluşturuluyor…',
    },
    manage: {
      iconLabel: 'İkon',
      backToList: 'Workspace’lere dön',
      loading: 'Workspace yükleniyor…',
      loadErrorTitle: 'Workspace yüklenemedi',
      memberCount: 'üye',
      settingsTitle: 'Workspace ayarları',
      settingsDescription: 'Workspace adını ve adresini (slug) güncelleyin.',
      pageDescription: 'Workspace kimliği, panoları, üyeleri ve işlemlerini yönetin.',
      generalTitle: 'Genel',
      generalDescription: 'Workspace adı, adresi ve ikonunu düzenleyin.',
      actionsTitle: 'Workspace işlemleri',
      actionsDescription: 'Workspace arşivleme ve kalıcı silme işlemleri.',
      archiveTitle: 'Arşiv durumu',
      deleteTitle: 'Kalıcı silme',
      readonlyNote: 'Bu ayarları değiştirmek için workspace yöneticisi olmanız gerekir.',
      ownerOnlyNote:
        'Arşivleme ve kalıcı silme işlemleri yalnızca workspace sahibi tarafından yapılabilir.',
      nameLabel: 'Workspace adı',
      nameDescription: 'Workspace switcher ve başlıklarda görünen ad.',
      namePlaceholder: 'Örn. Pazarlama Ekibi',
      slugLabel: 'Adres (slug)',
      slugDescription: 'Workspace URL ve davet bağlamında kullanılan kısa adres.',
      slugPlaceholder: 'orn-pazarlama-ekibi',
      slugHelp: 'Yalnızca küçük harf, rakam ve tire.',
      iconDescription: 'Header ve switcher içinde görünen workspace ikonunu seçin.',
      save: 'Kaydet',
      saving: 'Kaydediliyor…',
      saved: 'Değişiklikler kaydedildi.',
      noChange: 'Değişiklik yok.',
      dangerTitle: 'Tehlikeli bölge',
      dangerDescription: 'Workspace’i arşivlemek listeden kaldırır; içerik silinmez.',
      archiveButton: 'Workspace’i arşivle',
      archiving: 'Arşivleniyor…',
      archiveConfirmTitle: 'Workspace arşivlensin mi?',
      archiveConfirmDescription:
        'Bu workspace listenizden kaldırılır. İçerik silinmez; ileride bir yöneticinin geri alması gerekir.',
      archiveConfirm: 'Arşivle',
      deleteAction: 'Workspace’i kalıcı sil',
      deleteDialogTitle: 'Workspace’i kalıcı sil',
      deleteDialogDescription:
        'Bu işlem geri alınamaz. Workspace ve tüm üyeleri, davetleri, panoları kalıcı olarak silinir.',
      deleteConfirmNameLabel: 'Workspace adı',
      deleteConfirmNamePrompt: 'Onaylamak için workspace adını yazın:',
      deleteConfirm: 'Kalıcı sil',
      deleting: 'Siliniyor…',
    },
  },
  members: {
    sectionTitle: 'Üyeler',
    sectionDescription: 'Workspace üyelerini görüntüleyin; rollerini değiştirin veya çıkarın.',
    roleInfoLabel: 'Workspace rol bilgisi',
    roleInfo:
      'Workspace rolü genel erişimi belirler. Sahip ve Yönetici üyeleri yönetir; Üye panolarda çalışabilir; Misafir yalnızca davet edildiği panolara erişir.',
    loading: 'Üyeler yükleniyor…',
    loadErrorTitle: 'Üyeler yüklenemedi',
    empty: 'Üye yok.',
    roleLabel: 'Rol',
    youBadge: 'Bu sizsiniz',
    ownerBadge: 'Sahip',
    remove: 'Çıkar',
    removing: 'Çıkarılıyor…',
    removeConfirmTitle: 'Üye çıkarılsın mı?',
    removeConfirmDescription:
      'Bu kişi workspace’ten çıkarılacak. Tekrar erişmesi için yeniden davet edilmesi gerekir.',
    removeConfirm: 'Çıkar',
    leave: 'Workspace’ten ayrıl',
    leaving: 'Ayrılınıyor…',
    leaveConfirmTitle: 'Workspace’ten ayrılınsın mı?',
    leaveConfirmDescription:
      'Bu workspace’e erişiminizi kaybedersiniz. Tekrar erişmek için yeniden davet edilmeniz gerekir.',
    leaveConfirm: 'Ayrıl',
  },
  board: {
    listSectionTitle: 'Panolar',
    listSectionDescription: 'Bu workspace’teki panolar.',
    loading: 'Panolar yükleniyor…',
    loadErrorTitle: 'Panolar yüklenemedi',
    empty: 'Henüz pano yok — ilkini oluştur.',
    archivedBadge: 'Arşivli',
    newButton: 'Pano oluştur',
    roleBadgePrefix: 'Rol:',
    create: {
      iconLabel: 'İkon',
      title: 'Yeni pano',
      description: 'Bir ad verin; bu panonun yöneticisi siz olursunuz.',
      nameLabel: 'Pano adı',
      namePlaceholder: 'Örn. Ürün Yol Haritası',
      submit: 'Oluştur',
      submitting: 'Oluşturuluyor…',
    },
    settings: {
      open: 'Pano ayarları',
      dialogTitle: 'Pano ayarları',
      dialogDescription: 'Üyeleri, davetleri ve etiketleri yönetin.',
      dropdownTitle: 'Pano ayarları',
      membersDropdownTitle: 'Üyeler ve davetler',
      labelsDropdownTitle: 'Pano etiketleri',
      pendingRequestsBadge: (count: number) =>
        `${count} bekleyen erişim talebi`,
      backToBoard: 'Panoya dön',
      generalTitle: 'Genel',
      generalDescription: 'Pano adı ve ikonunu düzenleyin.',
      nameTitle: 'Pano adı',
      nameDescription: 'Header, switcher ve pano listelerinde görünen ad.',
      tabMembers: 'Üyeler',
      tabInvitations: 'Davetler',
      tabAccessRequests: 'Talepler',
      tabIcon: 'İkon',
      iconTitle: 'Pano ikonu',
      iconDescription: 'Header ve switcher içinde görünen pano ikonunu seçin.',
      pageDescription: 'Pano ikonunu ve görünüm ayarlarını yönetin.',
      appearanceTitle: 'Görünüm',
      appearanceDescription: 'Pano yüzeyinin arka planını düzenleyin.',
      archiveTitle: 'Arşiv durumu',
      archiveDescription: 'Pano arşivlenince içerik korunur ve pano salt okunur hale gelir.',
      restoreDescription: 'Bu pano arşivli. Geri yükleyerek yeniden düzenlenebilir hale getirin.',
      readonlyNote: 'Bu ayarları değiştirmek için pano yöneticisi olmanız gerekir.',
      archivedNote: 'Arşivli panolarda ad, ikon ve arka plan değiştirilemez.',
      activeBadge: 'Aktif',
      tabBackground: 'Arka plan',
      tabActions: 'Pano işlemleri',
      actionsDescription: 'Pano adını değiştirme ve arşiv/geri yükleme işlemleri burada yönetilir.',
      backgroundDescription: 'Pano zemini için ortak gradient veya düz renk seçin.',
      membersTitle: 'Üyeler',
      membersDescription: 'Bu panonun üyelerini görüntüleyin; rollerini değiştirin veya çıkarın.',
      membersInfoLabel: 'Pano rol bilgisi',
      membersInfo:
        'Panoda açık rol varsa o kullanılır. Yoksa workspace Sahip/Yönetici panoda Yönetici, workspace Üye panoda Üye sayılır. Misafir yalnızca açıkça eklendiği panoya girer.',
      membersLoading: 'Üyeler yükleniyor…',
      membersLoadErrorTitle: 'Üyeler yüklenemedi',
      membersEmpty: 'Bu panoda üye yok.',
      inheritedNote: 'Workspace yöneticisi — düzenlenemez',
      roleLabel: 'Rol',
      youBadge: 'Bu sizsiniz',
      lastAdminNote: 'Tek pano yöneticisi — düşürülemez/çıkarılamaz',
      remove: 'Çıkar',
      removing: 'Çıkarılıyor…',
      removeConfirmTitle: 'Üye panodan çıkarılsın mı?',
      removeConfirmDescription:
        'Bu kişi panodan çıkarılır. Kartlardaki atamaları/izlemeleri korunur, ama pano erişimi olmadan kart işlemleri yapamaz.',
      removeConfirm: 'Çıkar',
      leave: 'Panodan ayrıl',
      leaving: 'Ayrılınıyor…',
      leaveConfirmTitle: 'Panodan ayrılınsın mı?',
      leaveConfirmDescription:
        'Bu panoya erişiminizi kaybedersiniz. Tekrar erişmek için yeniden eklenmeniz/davet edilmeniz gerekir.',
      leaveConfirm: 'Ayrıl',
      addTitle: 'Üye ekle',
      addDescription: 'E-posta ile panoya bir üye ekleyin veya davet gönderin.',
      addEmailLabel: 'E-posta',
      addEmailPlaceholder: 'ornek@eposta.com',
      addRoleLabel: 'Rol',
      addSubmit: 'Ekle',
      addSubmitting: 'Ekleniyor…',
      addedNotice: 'eklendi.',
      addedAsGuestNotice: 'workspace misafiri olarak eklendi.',
      invitedNotice: 'e-posta adresine davet gönderildi.',
      sentInvitationsTitle: 'Gönderilmiş davetler',
      sentInvitationsDescription: 'Yeni üye davet edin ve bekleyen davetleri yönetin.',
      invitationsInfoLabel: 'Pano davet bilgisi',
      invitationsInfo:
        'Pano daveti kabul edilince kişi workspace üyesi değilse önce Misafir yapılır, sonra bu panoya seçilen rolle eklenir.',
      pendingInvitationsTitle: 'Bekleyen davetler',
      invitationsLoadErrorTitle: 'Davetler yüklenemedi',
      noSentInvitations: 'Bekleyen davet yok.',
      accessRequestsTitle: 'Erişim talepleri',
      accessRequestsDescription:
        'Pano linkinden erişim isteyen kullanıcıları onaylayın veya reddedin.',
      accessRequestsInfoLabel: 'Pano erişim talebi bilgisi',
      accessRequestsInfo:
        'Paylaşılan pano linkinden gelen talepler yalnızca bu pano içindir. Onaylanırsa kullanıcı gerekirse workspace Misafir’i olur ve seçilen pano rolünü alır.',
      accessRequestsLoading: 'Erişim talepleri yükleniyor…',
      accessRequestsLoadErrorTitle: 'Erişim talepleri yüklenemedi',
      noAccessRequests: 'Bekleyen erişim talebi yok.',
      accessRequestRoleLabel: 'Onay rolü',
      accessRequestApprove: 'Onayla',
      accessRequestApproving: 'Onaylanıyor…',
      accessRequestReject: 'Reddet',
      accessRequestRejecting: 'Reddediliyor…',
      accessRequestMessageLabel: 'Mesaj',
      revoke: 'İptal et',
      revoking: 'İptal ediliyor…',
      revokeConfirmTitle: 'Davet iptal edilsin mi?',
      revokeConfirmDescription:
        'Bu davet geçersiz hale gelir. Kişi davet bağlantısını artık kullanamaz.',
      revokeConfirm: 'Daveti iptal et',
      invitedBy: 'Davet eden',
      expiresAt: 'Son tarih',
      labelsTitle: 'Etiketler',
      labelsDescription: 'Bu panonun etiket paletini yönetin.',
      labelsLoading: 'Etiketler yükleniyor…',
      labelsLoadErrorTitle: 'Etiketler yüklenemedi',
      labelsEmpty: 'Bu panoda etiket yok.',
      labelUnnamed: '(adsız)',
      labelNameLabel: 'Ad (isteğe bağlı)',
      labelNamePlaceholder: 'Örn. Acil',
      labelColorLabel: 'Renk',
      labelColorOf: 'Renk:',
      labelAdd: 'Etiket ekle',
      labelAdding: 'Ekleniyor…',
      labelEdit: 'Düzenle',
      labelSave: 'Kaydet',
      labelSaving: 'Kaydediliyor…',
      labelDelete: 'Sil',
      labelDeleting: 'Siliniyor…',
      labelDeleteConfirmTitle: 'Etiket silinsin mi?',
      labelDeleteConfirmDescription:
        'Bu etiket silinir ve tüm kartlardan kaldırılır. Geri alınamaz.',
      labelDeleteConfirm: 'Sil',
    },
    background: {
      title: 'Arka plan',
      tabs: {
        gradient: 'Gradient',
        solid: 'Düz renk',
      },
      default: 'Varsayılan',
      gradientNames: {
        sunset: 'Gün batımı',
        ocean: 'Okyanus',
        rainbow: 'Gökkuşağı',
        forest: 'Orman',
        lavender: 'Lavanta',
        sunrise: 'Gündoğumu',
        midnight: 'Gece yarısı',
        mint: 'Nane',
        aurora: 'Kuzey ışığı',
        coral: 'Mercan',
        lagoon: 'Lagun',
        ember: 'Kor',
        blossom: 'Çiçek',
        meadow: 'Çayır',
        dusk: 'Alacakaranlık',
        pearl: 'İnci',
        'trello-bubble': 'Trello Açık mavi',
        'trello-snow': 'Trello Mavi',
        'trello-ocean': 'Trello Koyu mavi',
        'trello-crystal': 'Trello Koyu mor',
        'trello-rainbow': 'Trello Mor',
        'trello-peach': 'Trello Turuncu',
        'trello-flower': 'Trello Pembe',
        'trello-earth': 'Trello Yeşil',
        'trello-alien': 'Trello Gri',
        'trello-volcano': 'Trello Kırmızı',
      },
      colorNames: {
        kirmizi: 'Kırmızı',
        turuncu: 'Turuncu',
        sari: 'Sarı',
        lime: 'Lime',
        yesil: 'Yeşil',
        sky: 'Gök mavisi',
        mavi: 'Mavi',
        indigo: 'İndigo',
        mor: 'Mor',
        pembe: 'Pembe',
        gri: 'Gri',
        siyah: 'Siyah',
        beyaz: 'Beyaz',
        'kirik-beyaz': 'Kırık beyaz',
        fildisi: 'Fildişi',
        'buz-beyazi': 'Buz beyazı',
        gumus: 'Gümüş',
      },
    },
    filter: {
      labelsTitle: 'Etikete göre filtrele',
      clearLabels: 'Temizle',
      allLabels: 'Tümü',
      unnamedLabel: '(adsız)',
      noLabels: 'Bu panoda etiket yok.',
      dueDateTitle: 'Tarihe göre filtrele',
      dueDateAll: 'Tümü',
      dueDateOverdue: 'Süresi geçmiş',
      dueDateDay: 'Önümüzdeki gün',
      dueDateWeek: 'Önümüzdeki hafta',
      dueDateMonth: 'Önümüzdeki ay',
      dueDateNone: 'Bitiş tarihi yok',
      showArchivedLists: 'Arşivli listeleri göster',
      hideArchivedLists: 'Arşivli listeleri gizle',
      archivedListsToggle: 'Arşivli listeleri göster',
      archivedListCount: 'arşivli liste',
    },
    archive: {
      open: 'Arşivli öğeler',
      title: 'Arşivli öğeler',
      description: 'Bu panoda arşivlenen listeleri ve kartları yönetin.',
      showArchivedLists: 'Arşivli listeleri göster',
      showArchivedCards: 'Arşivli kartları göster',
      archivedListCount: 'arşivli liste',
      archivedCardCount: 'arşivli kart',
      listsTitle: 'Listeler',
      listsDescription: 'Arşivli listeler panoda gizlenir; geri yüklenince eski konumunda görünür.',
      noArchivedLists: 'Arşivli liste yok.',
      cardsTitle: 'Kartlar',
      cardsDescription: 'Arşivli kartlar panoda görünmez; geri yüklenince aktif listede görünür.',
      cardsLoading: 'Arşivli kartlar yükleniyor…',
      cardsLoadErrorTitle: 'Arşivli kartlar yüklenemedi',
      noArchivedCards: 'Arşivli kart yok.',
      restore: 'Geri yükle',
      moveAndRestore: 'Listeye taşı',
      moveTargetLabel: 'Hedef liste',
      noActiveLists: 'Önce aktif bir liste gerekli.',
      restoreFailed: 'Geri yükleme tamamlanamadı. Lütfen tekrar deneyin.',
    },
    detail: {
      backToWorkspace: 'Workspace’e dön',
      loading: 'Pano yükleniyor…',
      loadErrorTitle: 'Pano yüklenemedi',
      accessContextLoadErrorTitle: 'Pano bilgisi alınamadı',
      archivedNote: 'Bu pano arşivli — salt okunur.',
      rename: 'Pano adını değiştir',
      renamePlaceholder: 'Pano adı',
      renameSave: 'Kaydet',
      renameSaving: 'Kaydediliyor…',
      renameCancel: 'Vazgeç',
      archive: 'Panoyu arşivle',
      archiving: 'Arşivleniyor…',
      archiveConfirmTitle: 'Pano arşivlensin mi?',
      archiveConfirmDescription:
        'Bu pano arşivlenir ve salt okunur olur. İçerik silinmez; bir yönetici geri alabilir.',
      archiveConfirm: 'Arşivle',
      restore: 'Panoyu geri yükle',
      restoring: 'Geri yükleniyor…',
      emptyBoard: 'Bu panoda henüz liste yok.',
      accessRequest: {
        title: 'Bu pano özel',
        description: 'Erişmek için bu panonun yöneticilerine istek gönderin.',
        targetLabel: 'Erişmek istediğiniz pano',
        signedInAs: 'Şu hesapla giriş yaptınız:',
        disclaimer:
          'Talep gönderdiğinizde adınız ve e-posta adresiniz pano yöneticileriyle paylaşılır.',
        submitButton: 'Talep gönder',
        submittingButton: 'Talep gönderiliyor…',
        pendingButton: 'Talep gönderildi',
      },
    },
    skeleton: {
      loading: 'Pano yükleniyor…',
    },
    topBar: {
      eyebrow: 'Pano',
      archivedBadge: 'Arşivli',
      favorite: 'Favorilere ekle',
      unfavorite: 'Favorilerden çıkar',
      favoriteSoon: 'Favoriler yakında geliyor.',
      invite: 'Davet et',
      share: 'Paylaş',
      shareCopied: 'Pano bağlantısı kopyalandı.',
      shareFailed: 'Bağlantı kopyalanamadı.',
      members: 'Üyeler',
      membersWithRequests: (count: number) =>
        `Üyeler — ${count} bekleyen erişim talebi`,
      labels: 'Etiketler',
      settings: 'Ayarlar',
      search: 'Bu panoda ara',
      searchSoon: 'Pano içi arama yakında geliyor.',
      activity: 'Pano işlemleri',
      activitySoon: 'Pano işlemleri yakında geliyor.',
      assignedToMe: 'Bana atanan kartlar',
      more: 'Diğer işlemler',
      menuRename: 'Pano adını değiştir',
      menuArchive: 'Panoyu arşivle',
      menuRestore: 'Panoyu geri yükle',
      menuSettings: 'Pano ayarları',
    },
    activity: {
      title: 'Pano aktivitesi',
      description: 'Bu panoda yapılan son işlemler.',
      empty: 'Henüz pano aktivitesi yok.',
      loading: 'Aktivite yükleniyor…',
      loadErrorTitle: 'Aktivite yüklenemedi',
      unknownActor: 'Bir kullanıcı',
      loadMore: 'Daha fazla yükle',
      loadingMore: 'Yükleniyor…',
    },
    column: {
      addList: 'Liste ekle',
      addListPlaceholder: 'Liste adı',
      addListSubmit: 'Ekle',
      addListSubmitting: 'Ekleniyor…',
      renamePlaceholder: 'Liste adı',
      renameSave: 'Kaydet',
      renameSaving: 'Kaydediliyor…',
      archive: 'Listeyi arşivle',
      archiving: 'Arşivleniyor…',
      archiveConfirmTitle: 'Liste arşivlensin mi?',
      archiveConfirmDescription:
        'Bu liste arşivlenir. İçindeki kartlar korunur; bir üye listeyi geri alabilir.',
      archiveConfirm: 'Arşivle',
      restore: 'Listeyi geri yükle',
      restoring: 'Geri yükleniyor…',
      archivedLabel: 'Arşivli',
      empty: 'Bu listede kart yok.',
      cardCount: 'kart',
      members: 'Pano üyeleri',
      more: 'Liste işlemleri',
      collapse: 'Listeyi daralt',
      expand: 'Listeyi genişlet',
      menuRename: 'Yeniden adlandır',
      menuArchive: 'Listeyi arşivle',
      menuRestore: 'Listeyi geri yükle',
    },
    list: {
      colorPicker: {
        title: 'Liste rengini değiştir',
        clear: 'Rengi kaldır',
        colors: {
          kirmizi: 'Kırmızı',
          turuncu: 'Turuncu',
          sari: 'Sarı',
          lime: 'Lime',
          yesil: 'Yeşil',
          sky: 'Gök Mavisi',
          mavi: 'Mavi',
          mor: 'Mor',
          pembe: 'Pembe',
          gri: 'Gri',
        },
      },
      iconPicker: {
        title: 'Liste ikonunu değiştir',
        clearIcon: 'İkonu kaldır',
        clearColor: 'İkon rengini sıfırla',
        icons: {
          circle: 'Daire',
          'circle-dot': 'Dolu daire',
          'circle-dashed': 'Kesik daire',
          'circle-check': 'Onaylı daire',
          'circle-alert': 'Uyarı dairesi',
          check: 'Tik',
          'square-check': 'Onay kutusu',
          list: 'Liste',
          'list-todo': 'Yapılacaklar',
          'list-checks': 'Kontrol listesi',
          layers: 'Katmanlar',
          play: 'Başlat',
          pause: 'Duraklat',
          hourglass: 'Kum saati',
          timer: 'Zamanlayıcı',
          'alarm-clock': 'Alarm',
          star: 'Yıldız',
          flag: 'Bayrak',
          bookmark: 'Yer imi',
          tag: 'Etiket',
          pin: 'Raptiye',
          sparkles: 'Parıltı',
          lightbulb: 'Fikir',
          heart: 'Kalp',
          'thumbs-up': 'Beğeni',
          clock: 'Saat',
          calendar: 'Takvim',
          user: 'Kullanıcı',
          users: 'Kullanıcılar',
          bell: 'Zil',
          'message-square': 'Mesaj',
          mail: 'E-posta',
          briefcase: 'Çanta',
          target: 'Hedef',
          rocket: 'Roket',
          zap: 'Hızlı',
          trophy: 'Kupa',
          award: 'Ödül',
          'trending-up': 'Yükseliş',
          activity: 'Etkinlik',
          folder: 'Klasör',
          'file-text': 'Belge',
          paperclip: 'Ataç',
          inbox: 'Gelen kutusu',
          archive: 'Arşiv',
          package: 'Paket',
          'triangle-alert': 'Uyarı',
          lock: 'Kilit',
          bug: 'Hata',
          wrench: 'Anahtar',
          hammer: 'Çekiç',
          gift: 'Hediye',
          coffee: 'Kahve',
        },
        colors: {
          kirmizi: 'Kırmızı',
          turuncu: 'Turuncu',
          sari: 'Sarı',
          lime: 'Lime',
          yesil: 'Yeşil',
          sky: 'Gök Mavisi',
          mavi: 'Mavi',
          indigo: 'İndigo',
          mor: 'Mor',
          pembe: 'Pembe',
          gri: 'Gri',
          siyah: 'Siyah',
        },
      },
    },
    dnd: {
      // Drag handles + the keyboard/button alternative (card ⋮ "move", column ⋮ "move left/right").
      listDragHandleLabel: 'Listeyi sürükleyerek taşı',
      move: 'Taşı',
      moveToList: 'Listeye taşı',
      moveToListEnd: 'sonuna ekle',
      moveLeft: 'Sola taşı',
      moveRight: 'Sağa taşı',
      // aria-live announcements while dragging (best-effort).
      announceCardGrabbed: 'Kart kaldırıldı. Bırakmak için fareyi taşıyın.',
      announceListGrabbed: 'Liste kaldırıldı. Bırakmak için fareyi taşıyın.',
      announceQuickNoteGrabbed:
        'Hızlı not kaldırıldı. Karta çevirmek için bir listeye bırakın.',
      announceDropped: 'Bırakıldı.',
    },
    // Hızlı Notlar paneli (DEM-205) — pano ekranında açılıp kapanan kişisel
    // "Gelen Kutusu" paneli; bir not listeye sürüklenince karta dönüşür.
    quickNotes: {
      panelTitle: 'Hızlı Notlar',
      toggle: 'Hızlı Notlar',
      open: 'Hızlı Notlar panelini aç',
      close: 'Hızlı Notlar panelini kapat',
      composerTitle: 'Yeni hızlı not',
      addPlaceholder: 'Bir hızlı not yazın…',
      addSubmit: 'Ekle',
      addSubmitting: 'Ekleniyor…',
      editPlaceholder: 'Notu düzenle…',
      editSubmit: 'Kaydet',
      editSaving: 'Kaydediliyor…',
      editAction: 'Düzenle',
      deleteAction: 'Sil',
      deleteConfirmTitle: 'Not silinsin mi?',
      deleteConfirmBody: 'Bu hızlı not kalıcı olarak silinir. Bu işlem geri alınamaz.',
      deleteConfirmAction: 'Sil',
      emptyTitle: 'Henüz hızlı not yok',
      emptyDescription:
        'Yukarıdan bir not ekleyin; sonra panodaki bir listeye sürükleyerek karta çevirin.',
      loadErrorTitle: 'Hızlı notlar yüklenemedi',
      dragHint: 'Bir listeye sürükleyerek karta çevir',
      dragLabel: (content: string) => `Hızlı notu sürükle: ${content}`,
      convertError: 'Not karta dönüştürülemedi. Lütfen tekrar deneyin.',
      actionError: 'İşlem tamamlanamadı. Lütfen tekrar deneyin.',
    },
    // Phase 4 optimistic UI — shared destructive / neutral toast copy used by every
    // board/list/card collaborative mutation (08-web-ve-mobil.md §8.1.9, 05-board-mekanigi.md §5.2).
    // Drag-drop reuses these (the older `dnd.error` / `dnd.conflict` copy was consolidated here).
    optimistic: {
      error: 'Değişiklik kaydedilemedi. Lütfen tekrar deneyin.',
    },
    conflict: {
      refreshed: 'Pano başka bir yerde güncellendi; yeniden yüklendi.',
    },
    card: {
      addCard: 'Kart ekle',
      addCardPlaceholder: 'Kart için bir başlık girin…',
      addCardSubmit: 'Ekle',
      addCardSubmitting: 'Ekleniyor…',
      addCardCancel: 'Vazgeç',
      edit: 'Kartı düzenle',
      completeToggle: 'Kartı tamamlandı olarak işaretle',
      completeUntoggle: 'Tamamlandı işaretini kaldır',
      archive: 'Kartı arşivle',
      archiving: 'Arşivleniyor…',
      archiveConfirmTitle: 'Kart arşivlensin mi?',
      archiveConfirmDescription: 'Bu kart arşivlenir ve panodan kaldırılır.',
      archiveConfirm: 'Arşivle',
      unnamedLabel: 'Etiket',
      context: {
        coverColor: 'Kapak',
        coverColorSection: 'Renk',
        coverColorOf: 'Kapak rengi:',
        coverColorClear: 'Rengi kaldır',
        coverImageSection: 'Fotoğraf',
        coverImageUpload: 'Kapak fotoğrafı yükle',
        coverImageClear: 'Kapak fotoğrafını kaldır',
        coverImageUploadFailed: 'Kapak fotoğrafı yüklenemedi.',
        labels: 'Etiketler',
        noLabels: 'Bu panoda etiket yok.',
        members: 'Sorumlular',
        membersHint: 'Üyeler arasından karta sorumlu ata',
        noMembers: 'Atanabilecek pano üyesi yok.',
        dueDate: 'Son tarih',
        dueCurrent: 'Şu an',
        dueEmpty: 'Son tarih yok',
        dueClear: 'Tarihi kaldır',
      },
      contextDueToday: 'Bugün',
      contextDueTomorrow: 'Yarın',
      contextDueWeekend: 'Bu hafta sonu',
      contextDueNextWeek: 'Gelecek hafta',
      dueLabel: 'Son tarih',
      overdueBadge: 'Gecikti',
      dueTooltip: 'Son tarih',
      overdueTooltip: 'Süresi geçti',
      dueSoonTooltip: 'Son tarih yaklaşıyor',
      descriptionTooltip: 'Açıklama var',
      labelsTooltip: 'Etiketler',
      checklistTooltip: 'Yapılacaklar',
      commentsTooltip: 'Yorumlar',
      attachmentsTooltip: 'Ekler',
      membersTooltip: 'Sorumlular',
      membersMore: 'sorumlu daha',
      coverImageAlt: (cardTitle: string) => `${cardTitle} — kapak görseli`,
      open: 'Kartı aç',
      editDialogTitle: 'Kartı düzenle',
      editDialogReadonlyTitle: 'Kart',
      titleLabel: 'Başlık',
      titlePlaceholder: 'Kart başlığı',
      descriptionLabel: 'Açıklama',
      descriptionPlaceholder: 'Bu kart hakkında notlar…',
      dueAtLabel: 'Son tarih',
      noDescription: 'Açıklama yok.',
      noDueAt: 'Son tarih yok.',
      save: 'Kaydet',
      saving: 'Kaydediliyor…',
      noChange: 'Değişiklik yok.',
      close: 'Kapat',
    },
  },
  card: {
    detail: {
      loading: 'Kart yükleniyor…',
      loadErrorTitle: 'Kart yüklenemedi',
      notFound: 'Kart bulunamadı.',
      close: 'Kapat',
      archivedNote: 'Bu kart arşivli — salt okunur.',
      archive: 'Kartı arşivle',
      archiving: 'Arşivleniyor…',
      restore: 'Kartı geri yükle',
      restoring: 'Geri yükleniyor…',
      titleLabel: 'Kart başlığı',
      titleSave: 'Kaydet',
      titleSaving: 'Kaydediliyor…',
      titleCancel: 'Vazgeç',
      editTitle: 'Başlığı düzenle',
      descriptionTitle: 'Açıklama',
      descriptionPlaceholder: 'Bu kart hakkında notlar…',
      descriptionEmpty: 'Açıklama yok.',
      descriptionAdd: 'Açıklama ekle',
      descriptionSave: 'Kaydet',
      descriptionSaving: 'Kaydediliyor…',
      dueTitle: 'Son tarih',
      dueEmpty: 'Son tarih yok.',
      dueLabel: 'Son tarih',
      duePlaceholder: 'YYYY-AA-GG',
      dueCalendarSelect: 'Takvimden seç',
      dueSave: 'Kaydet',
      dueSaving: 'Kaydediliyor…',
      dueClear: 'Kaldır',
      dueEdit: 'Düzenle',
      dueAdd: 'Son tarih ekle',
      descriptionEmptyPrompt: 'Açıklama ekle…',
      descriptionEditAction: 'Düzenle',
      descriptionCancelAction: 'Vazgeç',
      // Card detail modal chrome (Faz 2.7C).
      modal: {
        dialogTitle: 'Kart ayrıntıları',
        archivedBadge: 'Arşivli',
        overdueBadge: 'Gecikti',
        breadcrumbBoard: 'Pano',
        breadcrumbList: 'Liste',
        notifications: 'Bildirimler',
        notificationsSoon: 'Kart bildirimleri yakında geliyor.',
        copyLink: 'Bağlantıyı kopyala',
        linkCopied: 'Bağlantı kopyalandı',
        more: 'Diğer işlemler',
        menuMove: 'Kartı taşı',
        menuCopy: 'Kartı kopyala',
        menuArchive: 'Kartı arşivle',
        menuRestore: 'Kartı geri yükle',
        completeToggle: 'Kartı tamamlandı olarak işaretle',
        completeUntoggle: 'Tamamlandı işaretini kaldır',
        coverColor: 'Kapak',
        coverColorPickerTitle: 'Kapak rengi',
        coverColorOf: 'Kapak rengi:',
        coverColorClear: 'Kaldır',
        coverImageUpload: 'Kapak fotoğrafı yükle',
        coverImageClear: 'Kapak fotoğrafını kaldır',
        coverImageCurrent: 'Kapak fotoğrafı',
        coverImageUploadFailed: 'Kapak fotoğrafı yüklenemedi.',
        coverImageTooLarge: 'Kapak fotoğrafı en fazla 50 MB olabilir.',
        addMeta: 'Ekle',
        membersChip: 'Üye',
        labelsChip: 'Etiket',
        dueChip: 'Son tarih',
        attachmentAdd: 'Dosya ekle',
      },
      // Rich text editor labels (passed to @pusula/ui RichTextEditor — no hardcoded copy there).
      richText: {
        bold: 'Kalın',
        italic: 'İtalik',
        strike: 'Üstü çizili',
        code: 'Kod',
        heading1: 'Başlık 1',
        heading2: 'Başlık 2',
        heading3: 'Başlık 3',
        bulletList: 'Madde işaretli liste',
        orderedList: 'Numaralı liste',
        link: 'Bağlantı',
        linkPrompt: 'Bağlantı adresi (URL):',
      },
      // Right-panel tabs + composer.
      tabs: {
        comments: 'Yorumlar',
        activity: 'Aktivite',
        attachments: 'Ekler',
        all: 'Tümü',
      },
      composer: {
        placeholder: 'Yorum yaz, @ ile etiketle…',
        submit: 'Gönder',
        submitting: 'Gönderiliyor…',
        mentionEmpty: 'Eşleşen kullanıcı yok',
      },
      attachments: {
        empty: 'Henüz ek yok.',
      },
    },
    members: {
      title: 'Üyeler',
      infoLabel: 'Kart üyesi bilgisi',
      info: 'Sorumlu ve İzleyen kart ilişkileridir, erişim yetkisi vermez. Karta eklenen kişi panoyu zaten görebiliyor olmalıdır.',
      empty: 'Bu kartta üye yok.',
      addAction: 'Üye ekle',
      memberLabel: 'Üye',
      roleLabel: 'Rol',
      addSubmit: 'Ekle',
      adding: 'Ekleniyor…',
      cancel: 'Vazgeç',
      remove: 'Çıkar',
      removing: 'Çıkarılıyor…',
      noBoardMembers: 'Eklenebilecek başka pano üyesi yok.',
      watchSelf: 'Bu kartı izle',
      unwatchSelf: 'İzlemeyi bırak',
      watching: 'İşleniyor…',
    },
    labels: {
      title: 'Etiketler',
      empty: 'Bu kartta etiket yok.',
      addAction: 'Etiket ekle/kaldır',
      cancel: 'Kapat',
      remove: 'Kaldır',
      add: 'Ekle',
      working: 'İşleniyor…',
      unnamed: '(adsız)',
      createTitle: 'Yeni etiket',
      createColorLabel: 'Renk',
      createNameLabel: 'Ad (isteğe bağlı)',
      createNamePlaceholder: 'Örn. Acil',
      createSubmit: 'Etiket oluştur',
      creating: 'Oluşturuluyor…',
      colorOf: 'Renk:',
    },
    checklist: {
      title: 'Yapılacaklar',
      empty: 'Bu kartta yapılacak listesi yok.',
      addAction: 'Liste ekle',
      addTitlePlaceholder: 'Liste adı',
      addSubmit: 'Ekle',
      adding: 'Ekleniyor…',
      cancel: 'Vazgeç',
      rename: 'Yeniden adlandır',
      renameSave: 'Kaydet',
      renameSaving: 'Kaydediliyor…',
      renamePlaceholder: 'Liste adı',
      delete: 'Listeyi sil',
      deleting: 'Siliniyor…',
      deleteConfirmTitle: 'Liste silinsin mi?',
      deleteConfirmDescription: 'Bu yapılacaklar listesi ve içindeki maddeler silinir.',
      deleteConfirm: 'Sil',
      progress: 'maddeden',
      progressDone: 'tamamlandı',
      itemAddAction: 'Madde ekle',
      itemPlaceholder: 'Bir madde ekle…',
      itemAddSubmit: 'Ekle',
      itemAdding: 'Ekleniyor…',
      itemCancel: 'Vazgeç',
      itemEdit: 'Düzenle',
      itemSave: 'Kaydet',
      itemSaving: 'Kaydediliyor…',
      itemDelete: 'Sil',
      itemDeleting: 'Siliniyor…',
      itemToggleLabel: 'Tamamlandı olarak işaretle',
      overallProgressLabel: 'Toplam ilerleme',
      checklistProgressLabel: 'Liste ilerlemesi',
    },
    comments: {
      title: 'Yorumlar',
      empty: 'Henüz yorum yok.',
      addPlaceholder: 'Bir yorum yazın…',
      addSubmit: 'Yorum ekle',
      adding: 'Ekleniyor…',
      deletedPlaceholder: 'Bu yorum silindi.',
      editedSuffix: '(düzenlendi)',
      edit: 'Düzenle',
      editSave: 'Kaydet',
      editSaving: 'Kaydediliyor…',
      editCancel: 'Vazgeç',
      delete: 'Sil',
      deleting: 'Siliniyor…',
      deleteConfirmTitle: 'Yorum silinsin mi?',
      deleteConfirmDescription: 'Bu yorum silinir; yerine "silindi" notu görünür.',
      deleteConfirm: 'Sil',
      unknownAuthor: 'Bilinmeyen kullanıcı',
    },
    activity: {
      title: 'İşlemler',
      empty: 'Henüz aktivite yok.',
      loadErrorTitle: 'İşlemler yüklenemedi',
      unknownActor: 'Bir kullanıcı',
    },
  },
  activityDetail: {
    title: 'Aktivite detayı',
    description: 'Seçilen aktivitenin tüm ayrıntıları.',
    infoLabel: 'Ayrıntıları gör',
    metaActor: 'Kişi',
    metaDate: 'Tarih',
    metaCategory: 'Kategori',
    metaType: 'Tür kodu',
    metaId: 'Kayıt no',
    changesTitle: 'Değişiklikler',
    changesEmpty: 'Bu olay için alan bazlı değişiklik kaydı yok.',
    rawTitle: 'Ham veri',
    emptyValue: '—',
  },
  invitations: {
    inviteAction: 'Üye davet et',
    inviteDialogTitle: 'Workspace’e üye davet et',
    inviteDialogDescription: 'Davet edilen kişiye e-posta ile davet bağlantısı gönderilir.',
    inviteEmailLabel: 'E-posta',
    inviteEmailPlaceholder: 'ornek@eposta.com',
    inviteSubmit: 'Davet gönder',
    inviteSubmitting: 'Gönderiliyor…',
    pendingTitle: 'Bekleyen davetler',
    workspaceGroupTitle: 'Workspace davetleri',
    boardGroupTitle: 'Pano davetleri',
    inWorkspace: 'workspace',
    accept: 'Kabul et',
    accepting: 'Kabul ediliyor…',
    decline: 'Reddet',
    declining: 'Reddediliyor…',
    invitedBy: 'Davet eden',
    expiresAt: 'Son tarih',
    sentTitle: 'Gönderilmiş davetler',
    sentDescription: 'Bu workspace’e gönderilen ve henüz yanıtlanmamış davetler.',
    loadErrorTitle: 'Davetler yüklenemedi',
    noSent: 'Bekleyen davet yok.',
    revoke: 'İptal et',
    revoking: 'İptal ediliyor…',
    revokeConfirmTitle: 'Davet iptal edilsin mi?',
    revokeConfirmDescription:
      'Bu davet geçersiz hale gelir. Kişi davet bağlantısını artık kullanamaz.',
    revokeConfirm: 'Daveti iptal et',
  },
  onboarding: {
    title: 'Pusula’ya hoş geldin',
    intro:
      'Çalışma alanların (workspace) ekiplerini ve panolarını gruplar; her panoda listeler ve kartlarla işleri takip edersin. Başlamak için ilk çalışma alanını oluştur.',
    hint: 'Otomatik bir çalışma alanı oluşturulamadı. Aşağıdan kendin oluşturabilirsin.',
    createCta: 'İlk çalışma alanını oluştur',
  },
  account: {
    pageTitle: 'Hesap ayarları',
    pageDescription: 'Profilini, parolanı ve hesabını yönet.',
    loading: 'Hesap bilgileri yükleniyor…',
    backToWorkspaces: 'Çalışma alanlarına dön',
    tabs: {
      profile: 'Profil',
      security: 'Güvenlik',
      notifications: 'Bildirimler',
    },
    notifications: {
      loading: 'Bildirim tercihleri yükleniyor…',
      channels: {
        title: 'Genel kanallar',
        description:
          'Workspace, pano veya kart için ayrıca tercih oluşturmadığın her bildirim bu ayarları kullanır.',
        inApp: 'Uygulama içi bildirim',
        email: 'E-posta',
        push: 'Push (mobil)',
        alwaysOn: 'her zaman açık',
        alwaysOnTooltip:
          'Uygulama içi bildirim merkezindeki çan rozeti her zaman çalışır; bu kanal kapatılamaz.',
      },
      mute: {
        title: 'Susturma seviyesi',
        none: 'Tüm bildirimleri al',
        mentionsOnly: 'Sadece sözedildiğimde',
        all: 'Tamamen sustur',
        bypassNote: 'Sözedilme (@) ve davetler her zaman geçer.',
      },
      matrix: {
        title: 'Bildirim tipleri',
        bulkAll: 'Hepsini aç',
        bulkNone: 'Hepsini kapat',
        bulkNoEmail: 'Sadece e-postayı kapat',
        muteBypassTooltip: 'Bu bildirim her zaman gönderilir — mute-bypass.',
        disabledByGlobalEmail: 'Önce genel e-postayı aç.',
        disabledByGlobalPush: 'Önce genel push bildirimini aç.',
        unavailable: 'Bu kanal bu bildirim tipi için mevcut değil.',
        typeToggleHint:
          'Şu an global kanal toggle’ı geçerli; tip-bazlı ayar yakında.',
        groups: {
          mentions: 'Atama & sözedilme',
          comment: 'Yorum',
          dueDate: 'Bitiş tarihi',
          lifecycle: 'Kart yaşam döngüsü',
          membership: 'Üyelik',
          invitations: 'Davet',
        },
        types: {
          cardAssigned: 'Bana atanma',
          mention: 'Sözedilme (@)',
          commentReply: 'Takipteki kartta yorum',
          commentUpdated: 'Yorum düzenlendi',
          commentDeleted: 'Yorum silindi',
          dueApproaching: 'Yaklaşan bitiş',
          dueOverdue: 'Geciken kart',
          dueChanged: 'Teslim tarihi değişti',
          // DEM-152 — granular kart-aktivite tipleri (eski `watchedActivity`
          // çöp kovasının yerini aldı).
          cardMoved: 'Kart taşındı',
          cardArchived: 'Kart arşivlendi',
          cardCompleted: 'Kart tamamlandı',
          cardCoverChanged: 'Kart kapağı değişti',
          cardMemberRemoved: 'Karttan çıkarıldım',
          attachmentAdded: 'Karta dosya eklendi',
          cardRenamed: 'Kart başlığı değişti',
          cardDescriptionChanged: 'Kart açıklaması değişti',
          cardLabelAdded: 'Kart etiketi eklendi',
          cardLabelRemoved: 'Kart etiketi kaldırıldı',
          checklistCreated: 'Yapılacaklar listesi eklendi',
          checklistItemAdded: 'Yapılacaklar maddesi eklendi',
          checklistItemRemoved: 'Yapılacaklar maddesi silindi',
          attachmentRemoved: 'Karttan dosya kaldırıldı',
          checklistItemCompleted: 'Yapılacaklar maddesi tamamlandı',
          memberRemoved: 'Üyelikten çıkarıldım',
          memberRoleChanged: 'Rolüm değişti',
          boardMemberAdded: 'Panoya eklendim',
          boardAccessRequested: 'Pano erişim talebi',
          boardInvitation: 'Pano daveti',
          workspaceInvitation: 'Çalışma alanı daveti',
        },
      },
      scopes: {
        title: 'Özelleştirilmiş kapsamlar',
        narrowestWins:
          'Daha dar kapsam (kart > pano > çalışma alanı) daha geniş olanı ezer. Burada listelenen her satır kendi kapsamı için "Genel kanallar" ayarlarını geçersiz kılar.',
        addNew: 'Yeni kapsam ekle',
        empty:
          'Henüz özel kapsam yok. Belirli bir çalışma alanı veya pano için ayrı tercih oluşturmak istersen aşağıdaki butonu kullan.',
        loading: 'Kapsam tercihleri yükleniyor…',
        loadFailed: 'Kapsam tercihleri yüklenemedi.',
        cardOverrideNote:
          'Kart bazlı sustur tercihleri kart detay menüsünden eklenir; burada düzenlenebilir veya kaldırılabilir.',
        scopeKind: {
          workspace: 'Çalışma alanı',
          board: 'Pano',
          card: 'Kart',
        },
        muteSummary: {
          none: 'Tüm bildirimler açık',
          mentionsOnly: 'Sadece sözedilme',
          all: 'Tamamen sustur',
        },
        emailOn: 'E-posta açık',
        emailOff: 'E-posta kapalı',
        pushOn: 'Push açık',
        pushOff: 'Push kapalı',
        removeOverride: 'Kaldır',
        removeOverrideAriaLabel: '{scope} için özel tercihi kaldır',
        removing: 'Kaldırılıyor…',
        edit: 'Düzenle',
        editDialogTitle: 'Kapsamı düzenle',
        editDialogDescription:
          'Bu kapsam için bildirim tercihlerini güncelle. Değişiklik bu kapsam ve altındakileri etkiler.',
      },
      addDialog: {
        title: 'Yeni kapsam ekle',
        description:
          'Bir çalışma alanı veya pano için ayrı bildirim tercihi oluştur. Kart bazlı tercihler kart detayından eklenir.',
        scopeKindLabel: 'Kapsam türü',
        scopeKindWorkspace: 'Çalışma alanı',
        scopeKindBoard: 'Pano',
        workspaceLabel: 'Çalışma alanı',
        workspacePlaceholder: 'Çalışma alanı seç…',
        boardLabel: 'Pano',
        boardPlaceholder: 'Pano seç…',
        boardDisabledHint: 'Önce çalışma alanı seç.',
        workspacesLoading: 'Çalışma alanları yükleniyor…',
        workspacesEmpty: 'Henüz çalışma alanı yok.',
        boardsLoading: 'Panolar yükleniyor…',
        boardsEmpty: 'Bu çalışma alanında pano yok.',
        preferenceTitle: 'Tercih',
        cancel: 'İptal',
        submit: 'Oluştur',
        submitting: 'Oluşturuluyor…',
        duplicateError: 'Bu kapsam için zaten bir tercih var.',
      },
      /**
       * Section 4 — push token cihaz listesi (Faz 10E / DEM-139). UI:
       * `notifications-devices-list.tsx`. Backend: `push.tokens.list` +
       * `push.tokens.revokeById`. Faz 7 mobile aktivasyonu olmadan veri
       * boş gelir → `empty*` metinleri devreye girer.
       */
      devices: {
        title: 'Push bildirim cihazları',
        description:
          'Mobil uygulamada giriş yaptığında cihaz buraya otomatik eklenir. Kullanmadığın bir cihazı listeden çıkarabilirsin.',
        loading: 'Cihazlar yükleniyor…',
        loadFailed: 'Cihazlar yüklenemedi.',
        emptyTitle: 'Henüz kayıtlı cihaz yok',
        emptyBody:
          'Mobil uygulamada giriş yaptığında otomatik eklenir. Şimdilik buradan yapacak bir şey yok.',
        remove: 'Çıkar',
        removing: 'Çıkarılıyor…',
        removeAriaLabel: '{device} cihazını listeden çıkar',
        unnamedDevice: {
          ios: 'iOS cihazı',
          android: 'Android cihazı',
          web: 'Web tarayıcı',
        },
        platform: {
          ios: 'iOS',
          android: 'Android',
          web: 'Web',
        },
        lastUsed: 'Son: {time}',
        registeredAt: 'Eklendi: {time}',
        revokeError: 'Cihaz kaldırılamadı. Lütfen tekrar deneyin.',
      },
      /**
       * Section 5 — sessiz saatler (Faz 10F / DEM-140). UI:
       * `notifications-quiet-hours-form.tsx`. Backend:
       * `notifications.preferences.upsert` (`quietFrom`/`quietTo`/`quietTimezone`).
       * Mute-bypass tipler (`mention`, davetler) pencerede de geçer.
       */
      quiet: {
        title: 'Sessiz saatler',
        description:
          'Belirlediğin aralıkta push ve e-posta gönderilmez. Uygulama içi bildirim her zaman çalışır.',
        toggleLabel: 'Sessiz saatleri aç',
        toggleHint:
          'Açıkken aşağıdaki saatler ve zaman dilimi geçerli olur; kapatınca pencere kaldırılır.',
        from: 'Başlangıç',
        to: 'Bitiş',
        timezone: 'Zaman dilimi',
        timezonePlaceholder: 'Zaman dilimi seç…',
        preview: 'Bildirimler {from}–{to} ({tz}) arasında push/e-posta göndermez.',
        bypassNote: 'Sözedilme (@) ve davetler her zaman anlık gelir.',
        invalidWindow: 'Başlangıç ve bitiş saatleri aynı olamaz.',
        savedAt: 'Son kaydedildi: {time}',
        /**
         * Sessiz saatler Select'inde gösterilen zaman dilimi seçenekleri.
         * Anahtar = IANA id (teknik, `value`); değer = kullanıcıya görünen
         * lokalize etiket.
         */
        timezoneOptions: {
          'Europe/Istanbul': 'Türkiye (Europe/Istanbul)',
          'Europe/London': 'Londra (Europe/London)',
          'Europe/Berlin': 'Berlin (Europe/Berlin)',
          'Europe/Paris': 'Paris (Europe/Paris)',
          'America/New_York': 'New York (America/New_York)',
          'America/Los_Angeles': 'Los Angeles (America/Los_Angeles)',
          'Asia/Tokyo': 'Tokyo (Asia/Tokyo)',
          'Asia/Dubai': 'Dubai (Asia/Dubai)',
          'Etc/UTC': 'UTC (Etc/UTC)',
        },
      },
      /**
       * Section 7 — Snooze (Faz 10H / DEM-142). Aksiyon kart detay
       * dropdown'ında alınır; AccountTabs Bildirimler sekmesinde sadece
       * "Aktif susturmalar" listesi gösterilir. Mute-bypass tipler
       * (mention + davet) snooze sırasında da geçer — `bypassNote` bunu
       * kullanıcıya bildirir.
       */
      snooze: {
        title: 'Aktif susturmalar',
        description:
          'Kart detayından geçici olarak susturduğun kartlar burada görünür. Süre dolduğunda otomatik açılır.',
        empty:
          'Aktif susturma yok. Bir kartı geçici olarak susturmak için kart detayındaki "Bildirimleri sustur" menüsünü kullan.',
        loading: 'Susturmalar yükleniyor…',
        loadFailed: 'Susturmalar yüklenemedi.',
        bypassNote: 'Sözedilme (@) ve davetler susturma sırasında da geçer.',
        cardLabel: 'Kart',
        remove: 'Kaldır',
        removing: 'Kaldırılıyor…',
        removeAriaLabel: '{card} susturmasını kaldır',
        removeError: 'Susturma kaldırılamadı. Lütfen tekrar deneyin.',
        button: 'Bildirimleri sustur',
        active: 'Susturuldu · Kalan {remaining}',
        durations: {
          '1h': '1 saatlik',
          '4h': '4 saatlik',
          '1d': '1 günlük',
          '1w': '1 haftalık',
          untilDate: 'Belirli tarihe kadar…',
        },
        unsnooze: 'Susturmayı kaldır',
        snoozeError: 'Kart susturulamadı. Lütfen tekrar deneyin.',
        unsnoozeError: 'Susturma kaldırılamadı. Lütfen tekrar deneyin.',
        untilDateDialogTitle: 'Belirli bir tarihe kadar sustur',
        untilDateDialogDescription:
          'Susturmanın biteceği tarihi seç. Maksimum 1 yıl sonrasına kadar bir tarih seçebilirsin.',
        untilDateLabel: 'Bitiş tarihi',
        untilDateSubmit: 'Sustur',
        untilDateCancel: 'İptal',
        untilDateInvalid: 'Tarih gelecekte olmalı ve 1 yıldan uzak olmamalı.',
      },
      /**
       * Section 6 — e-posta sıklığı / digest (Faz 10G — DEM-141). UI:
       * `notifications-digest-form.tsx`. Backend: `notifications.preferences.upsert`
       * `emailMode` alanı (`instant`/`hourly_digest`/`daily_digest`/`off`).
       * Mute-bypass tipler (mention + davet) her zaman anlık gönderilir —
       * `bypassNote` bu disiplini açıklar.
       */
      digest: {
        title: 'E-posta sıklığı',
        description:
          'E-posta bildirimleri ayrı ayrı gelsin mi yoksa belirli aralıklarla özet mi gelsin? Uygulama içi bildirimleri etkilemez.',
        instant: 'Anlık (her bildirim için ayrı mail)',
        hourly: 'Saatlik özet',
        daily: 'Günlük özet (sabah 08:00 UTC)',
        off: 'Hiç gönderme',
        bypassNote: 'Sözedilme (@) ve davetler her zaman anlık gönderilir.',
      },
      errors: {
        saveFailed: 'Tercihler kaydedilemedi. Lütfen tekrar deneyin.',
        loadFailed: 'Tercihler yüklenemedi.',
        deleteFailed: 'Kapsam kaldırılamadı. Lütfen tekrar deneyin.',
        permissionDenied: 'Bu tercihi düzenleme yetkin yok.',
        revokeFailed: 'Cihaz kaldırılamadı. Lütfen tekrar deneyin.',
      },
    },
    profile: {
      title: 'Profil',
      description: 'Adını ve avatarını güncelle.',
      nameLabel: 'Ad',
      namePlaceholder: 'Adınız',
      avatarLabel: 'Avatar',
      avatarUploadButton: 'Görsel yükle',
      avatarChangeButton: 'Görseli değiştir',
      avatarRemoveButton: 'Kaldır',
      avatarUploading: 'Yükleniyor…',
      avatarUploadHelp: 'JPG, PNG veya WebP — en fazla 10 MB.',
      imageLabel: 'veya görsel bağlantısı (URL)',
      imagePlaceholder: 'https://…',
      imageHelp: 'Dosya yüklemek yerine bir bağlantı da kullanabilirsin. Boş bırakırsan avatar kaldırılır.',
      avatarTypeError: 'Yalnızca JPG, PNG veya WebP yükleyebilirsin.',
      avatarSizeError: 'Görsel en fazla 10 MB olabilir.',
      avatarUploadError: 'Görsel yüklenemedi. Lütfen tekrar dene.',
      emailLabel: 'E-posta',
      emailReadonlyHelp: 'E-posta adresi şu an buradan değiştirilemiyor.',
      save: 'Kaydet',
      saving: 'Kaydediliyor…',
      saved: 'Profil güncellendi.',
      noChange: 'Değişiklik yok.',
    },
    password: {
      title: 'Parola',
      description: 'Hesabının parolasını değiştir.',
      currentLabel: 'Mevcut parola',
      newLabel: 'Yeni parola',
      confirmLabel: 'Yeni parola (tekrar)',
      placeholder: '••••••••',
      mismatch: 'Parolalar eşleşmiyor.',
      save: 'Parolayı değiştir',
      saving: 'Değiştiriliyor…',
      saved: 'Parolan değiştirildi. Diğer oturumların kapatıldı.',
    },
    security: {
      devices: {
        title: 'Bilinen cihazlar',
        description:
          'Bu cihazlardan oturum açtınız. Tanımadığınız bir cihaz varsa "Çıkış yap" diyerek o oturumu kapatın.',
        loading: 'Cihazlar yükleniyor…',
        loadFailed: 'Cihazlar yüklenemedi.',
        emptyTitle: 'Henüz bilinen cihaz yok',
        emptyBody:
          'Yeni bir tarayıcı veya cihazdan giriş yaptığınızda otomatik olarak burada listelenir.',
        signOut: 'Çıkış yap',
        signingOut: 'Çıkış yapılıyor…',
        signOutAriaLabel: '{device} cihazından çıkış yap',
        currentBadge: 'Bu oturum',
        location: 'Yaklaşık ağ',
        firstSeen: 'İlk: {date}',
        lastSeen: 'Son: {date}',
        revokeError: 'Cihaz kapatılamadı. Lütfen tekrar deneyin.',
        revokeSuccess: '{count} oturum kapatıldı.',
      },
    },
    danger: {
      title: 'Tehlikeli bölge',
      description: 'Hesabını kalıcı olarak sil. Bu işlem geri alınamaz.',
      deleteAction: 'Hesabımı sil',
      deleting: 'Siliniyor…',
      blockedOwnerTitle: 'Hesabını şu an silemezsin',
      blockedOwnerDescription:
        'Bir veya daha fazla çalışma alanının sahibisin. Hesabını silmeden önce o çalışma alanlarını sil, arşivle veya başka birine devret.',
      goToWorkspaces: 'Çalışma alanlarına git',
      dialogTitle: 'Hesabını kalıcı olarak sil',
      dialogDescription:
        'Bu işlem geri alınamaz. Hesabın, üyeliklerin ve sana ait içerik kalıcı olarak silinir. Onaylamak için parolanı gir.',
      passwordLabel: 'Parola',
      passwordPlaceholder: '••••••••',
      confirm: 'Hesabımı kalıcı sil',
    },
  },
  /**
   * Kart paylaşım linki (Faz 9 — DEM-124). Yönetim UI'si (üye paylaşım
   * linki oluştur/iptal/liste) + misafir sayfası (`/share/[token]`)
   * metinleri. Entity-bağımsız tutulur (i18n hazır).
   */
  share: {
    action: 'Paylaş',
    actionTooltip: 'Bu kartı zaman sınırlı bir bağlantı ile paydaşa gönder',
    viewerDisabledTooltip: 'Bu işlem için pano üyesi veya yöneticisi olmalısın',
    dialog: {
      title: 'Kartı paydaşla paylaş',
      description:
        'Hesabı olmayan birine bu kartı zaman sınırlı bir bağlantı ile gönder. Paydaş kartı görür ve yorum bırakabilir.',
      expiryLabel: 'Bağlantı geçerlilik süresi',
      expiry7: '7 gün',
      expiry30: '30 gün',
      expiry90: '90 gün',
      createAction: 'Bağlantı oluştur',
      creating: 'Oluşturuluyor…',
      createdTitle: 'Bağlantı hazır',
      createdHint: 'Bu bağlantıyı şimdi kopyala. Bağlantı bir daha gösterilmez.',
      copyAction: 'Bağlantıyı kopyala',
      copied: 'Bağlantı kopyalandı',
      copyFailed: 'Bağlantı kopyalanamadı',
      close: 'Kapat',
      createError: 'Bağlantı oluşturulamadı.',
    },
    list: {
      title: 'Aktif paylaşımlar',
      empty: 'Bu kart için henüz paylaşım bağlantısı yok.',
      loading: 'Bağlantılar yükleniyor…',
      loadError: 'Bağlantılar yüklenemedi.',
      columnTokenPrefix: 'Bağlantı',
      columnCreatedBy: 'Oluşturan',
      columnCreatedAt: 'Oluşturulma',
      columnExpiresAt: 'Geçerlilik',
      columnAccessCount: 'Erişim',
      columnLastAccessed: 'Son erişim',
      columnActions: 'İşlem',
      revokeAction: 'İptal et',
      revoking: 'İptal ediliyor…',
      revokedBadge: 'İptal edildi',
      revokedAt: 'İptal: {date}',
      revokeError: 'Bağlantı iptal edilemedi.',
      neverAccessed: 'Hiç açılmadı',
      openLink: 'Bağlantıya git',
      openLinkUnavailable: 'Bağlantı güvenlik gereği yeniden gösterilemez',
    },
    guest: {
      sharedWithYou: 'Bu kart sizinle paylaşıldı',
      workspaceLabel: 'Çalışma alanı:',
      sharedByLabel: 'Paylaşan:',
      unknownSharer: 'Bir kullanıcı',
      noRealtimeNotice:
        'Bu sayfa canlı güncellenmez. Yeni içeriği görmek için sayfayı yenileyin.',
      labelsHeading: 'Etiketler',
      membersHeading: 'Kart üyeleri',
      descriptionHeading: 'Açıklama',
      checklistsHeading: 'Kontrol listeleri',
      commentsHeading: 'Yorumlar',
      attachmentsHeading: 'Ekler',
      attachmentsDownloadNotice:
        'Ek dosyaları indirme paydaş bağlantısı için yakında etkin olacak.',
      commentPlaceholder: 'Yorumunuzu yazın…',
      submitComment: 'Yorum gönder',
      submitting: 'Gönderiliyor…',
      commentSent: 'Yorumunuz iletildi.',
      commentFailed: 'Yorum gönderilemedi. Lütfen tekrar deneyin.',
      commentTooShort: 'Yorum boş olamaz.',
      guestAuthorLabel: 'Misafir',
      deletedUserLabel: 'Silinmiş kullanıcı',
      emptyCommentsHint: 'Henüz yorum yok.',
      due: 'Son tarih:',
      completed: 'Tamamlandı',
    },
    error: {
      titleGeneric: 'Bağlantı kullanılamıyor',
      titleNotFound: 'Bağlantı bulunamadı',
      titleRevoked: 'Bağlantı iptal edildi',
      titleExpired: 'Bağlantının süresi doldu',
      titleCardArchived: 'Kart arşivlendi',
      titleCardDeleted: 'Kart silindi',
      description:
        'Bu bağlantı artık kullanılamaz. Paylaşan kişiden yeni bir bağlantı isteyebilirsin.',
      backHome: 'Pusula ana sayfasına git',
    },
  },
  /**
   * Kart eki "Ekler" sekmesi (Faz 11D — DEM-150). Dropzone, ek satırı,
   * önizleme dialogu ve kapak görseli seçici metinleri. Entity-bağımsız
   * tutulur (i18n hazır — hardcode metin yok).
   */
  attachment: {
    tabs: {
      attachments: 'Ekler',
    },
    dropzone: {
      idle: 'Dosya bırak veya seç',
      hint: 'Resim, PDF, Word/Excel/PowerPoint — en fazla 50 MB',
      active: 'Bırak yüklesin',
      uploading: (percent: number) => `Yükleniyor… %${percent}`,
      ariaLabel: 'Dosya yükle',
      disabledHint: 'Yalnızca okuyabilirsiniz',
      error: {
        tooLarge: 'Dosya çok büyük. En fazla 50 MB yükleyebilirsin.',
        mimeRejected: 'Bu dosya türü desteklenmiyor.',
      },
    },
    description: {
      label: 'Açıklama (isteğe bağlı)',
      placeholder: 'Bu dosya nedir? Ne için yüklüyorsun?',
      counter: (used: number, max: number) => `${used}/${max}`,
    },
    upload: {
      action: 'Yükle',
      uploading: 'Yükleniyor…',
    },
    actions: {
      preview: 'Önizle',
      download: 'İndir',
      openInNewTab: 'Yeni sekmede aç',
      edit: 'Açıklamayı düzenle',
      moreActions: 'Ek menüsü',
      delete: 'Sil',
      makeCover: 'Kapak yap',
      removeCover: 'Kapağı kaldır',
      save: 'Kaydet',
      cancel: 'İptal',
      cancelUpload: 'Yüklemeyi iptal et',
    },
    confirmDelete: {
      title: 'Eki sil',
      description: 'Bu ek kalıcı olarak silinecek. Bu işlem geri alınamaz.',
      confirm: 'Sil',
      cancel: 'Vazgeç',
    },
    cover: {
      badge: 'Kapak',
      tabColor: 'Kapak rengi',
      tabImage: 'Kapak görseli',
      imageEmpty: 'Bu kartta henüz görsel ek yok.',
      clear: 'Kapağı kaldır',
      selectAria: 'Kapak görseli olarak seç:',
    },
    empty: {
      title: 'Henüz ek yok.',
      description: 'Resim, PDF veya Office dosyası ekleyebilirsin.',
    },
    preview: {
      zoomIn: 'Yakınlaştır',
      zoomOut: 'Uzaklaştır',
      zoomReset: 'Sıfırla',
      zoomArea: 'Önizleme alanı — yön tuşlarıyla kaydırılabilir',
      loading: 'Önizleme yükleniyor…',
      error: 'Önizleme yüklenemedi.',
    },
    error: {
      uploadFailed: 'Dosya yüklenemedi. Lütfen tekrar deneyin.',
      commitFailed: 'Dosya kaydedilemedi. Lütfen tekrar deneyin.',
      deleteFailed: 'Ek silinemedi. Lütfen tekrar deneyin.',
      updateFailed: 'Açıklama güncellenemedi. Lütfen tekrar deneyin.',
      downloadFailed: 'Dosya indirilemedi. Lütfen tekrar deneyin.',
    },
    metaTooltip: 'Ekler',
  },
  // 404 — bulunamayan rota sayfası (`app/not-found.tsx`).
  notFound: {
    badge: '404',
    title: 'Yolunu mu kaybettin?',
    description:
      'Aradığın sayfa burada değil — taşınmış ya da hiç var olmamış olabilir. Pusula seni geri götürür.',
    backHome: 'Ana sayfaya dön',
  },
} as const;
