/**
 * User-facing copy for the web app, centralized in one place. This is a
 * placeholder for a real i18n layer (next-intl, etc.) — until then, components
 * read strings from here instead of inlining literals, so the eventual swap is a
 * single seam. Keep keys grouped by feature; values are plain Turkish strings.
 */

/** Display labels for workspace roles, used in badges and the role <Select>. */
export const workspaceRoleLabels = {
  owner: 'Sahip',
  admin: 'Yönetici',
  member: 'Üye',
  guest: 'Misafir',
} as const;

/** Display labels for board roles, used in badges. */
export const boardRoleLabels = {
  admin: 'Yönetici',
  member: 'Üye',
  viewer: 'İzleyici',
} as const;

/** Display labels for card-member roles (`assignee` / `watcher`). */
export const cardRoleLabels = {
  assignee: 'Sorumlu',
  watcher: 'İzleyen',
} as const;

export const strings = {
  common: {
    appName: 'Pusula',
    loading: 'Yükleniyor…',
    cancel: 'İptal',
    close: 'Kapat',
    retry: 'Tekrar dene',
    back: 'Geri',
    unknownError: 'Beklenmeyen bir hata oluştu. Lütfen tekrar deneyin.',
  },
  auth: {
    emailLabel: 'E-posta',
    emailPlaceholder: 'ornek@eposta.com',
    passwordLabel: 'Parola',
    passwordPlaceholder: '••••••••',
    nameLabel: 'Ad',
    namePlaceholder: 'Adınız',
    signIn: {
      title: 'Giriş yap',
      description: 'Hesabınızla devam edin.',
      submit: 'Giriş yap',
      submitting: 'Giriş yapılıyor…',
      noAccount: 'Hesabın yok mu?',
      goToSignUp: 'Kayıt ol',
      forgotPassword: 'Şifreni mi unuttun?',
      resetDone: 'Parolan güncellendi. Yeni parolanla giriş yapabilirsin.',
    },
    signUp: {
      title: 'Kayıt ol',
      description: 'Yeni bir hesap oluşturun.',
      submit: 'Kayıt ol',
      submitting: 'Kayıt olunuyor…',
      hasAccount: 'Zaten hesabın var mı?',
      goToSignIn: 'Giriş yap',
    },
    forgotPassword: {
      title: 'Şifreni mi unuttun?',
      description: 'E-posta adresini gir; sana bir sıfırlama bağlantısı gönderelim.',
      submit: 'Sıfırlama bağlantısı gönder',
      submitting: 'Gönderiliyor…',
      successTitle: 'Bağlantı yolda',
      // E-posta adresi araya konur — hesap kayıtlı mı belli edilmez (kullanıcı
      // listesi sızdırılmaz); kayıt yoksa Better Auth da sessizce başarı döner.
      successBodyPrefix: 'Eğer ',
      successBodySuffix:
        ' adresine bağlı bir hesap varsa, bir parola sıfırlama bağlantısı gönderdik. Gelen kutunu (ve spam klasörünü) kontrol et.',
      resend: 'Yeniden gönder',
      backToSignIn: 'Giriş ekranına dön',
    },
    resetPassword: {
      title: 'Yeni parola belirle',
      description: 'Hesabın için yeni bir parola gir.',
      newPasswordLabel: 'Yeni parola',
      confirmPasswordLabel: 'Yeni parola (tekrar)',
      passwordPlaceholder: '••••••••',
      passwordMismatch: 'Parolalar eşleşmiyor.',
      submit: 'Parolayı güncelle',
      submitting: 'Güncelleniyor…',
      successTitle: 'Parolan güncellendi',
      redirecting: 'Giriş ekranına yönlendiriliyorsun…',
      missingTokenTitle: 'Bağlantı geçersiz veya eksik',
      missingTokenBody:
        'Bu sıfırlama bağlantısı eksik ya da bozuk görünüyor. Yeni bir bağlantı isteyebilirsin.',
      requestNewLink: 'Yeni bağlantı iste',
      backToSignIn: 'Giriş ekranına dön',
    },
  },
  shell: {
    signOut: 'Çıkış',
    signingOut: 'Çıkış yapılıyor…',
    accountSettings: 'Hesap ayarları',
  },
  workspace: {
    listTitle: 'Workspace’lerin',
    loading: 'Workspace’ler yükleniyor…',
    loadErrorTitle: 'Workspace’ler yüklenemedi',
    redirecting: 'Workspace’ine yönlendiriliyorsun…',
    newButton: 'Yeni workspace',
    roleBadgePrefix: 'Rol:',
    openManage: 'Workspace’i aç',
    create: {
      title: 'Yeni workspace',
      description: 'Bir ad verin; sahibi siz olursunuz.',
      nameLabel: 'Workspace adı',
      namePlaceholder: 'Örn. Pazarlama Ekibi',
      submit: 'Oluştur',
      submitting: 'Oluşturuluyor…',
    },
    manage: {
      backToList: 'Workspace’lere dön',
      loading: 'Workspace yükleniyor…',
      loadErrorTitle: 'Workspace yüklenemedi',
      memberCount: 'üye',
      settingsTitle: 'Workspace ayarları',
      settingsDescription: 'Workspace adını ve adresini (slug) güncelleyin.',
      nameLabel: 'Workspace adı',
      namePlaceholder: 'Örn. Pazarlama Ekibi',
      slugLabel: 'Adres (slug)',
      slugPlaceholder: 'orn-pazarlama-ekibi',
      slugHelp: 'Yalnızca küçük harf, rakam ve tire.',
      save: 'Kaydet',
      saving: 'Kaydediliyor…',
      saved: 'Değişiklikler kaydedildi.',
      noChange: 'Değişiklik yok.',
      dangerTitle: 'Tehlikeli bölge',
      dangerDescription: 'Workspace’i arşivlemek listeden kaldırır; içerik silinmez.',
      archiveButton: 'Workspace’i arşivle',
      archiving: 'Arşivleniyor…',
      archiveConfirmTitle: 'Workspace arşivlensin mi?',
      archiveConfirmDescription:
        'Bu workspace listenizden kaldırılır. İçerik silinmez; ileride bir yöneticinin geri alması gerekir.',
      archiveConfirm: 'Arşivle',
      deleteAction: 'Workspace’i kalıcı sil',
      deleteDialogTitle: 'Workspace’i kalıcı sil',
      deleteDialogDescription:
        'Bu işlem geri alınamaz. Workspace ve tüm üyeleri, davetleri, panoları kalıcı olarak silinir.',
      deleteConfirmNameLabel: 'Workspace adı',
      deleteConfirmNamePrompt: 'Onaylamak için workspace adını yazın:',
      deleteConfirm: 'Kalıcı sil',
      deleting: 'Siliniyor…',
    },
  },
  members: {
    sectionTitle: 'Üyeler',
    sectionDescription: 'Workspace üyelerini görüntüleyin; rollerini değiştirin veya çıkarın.',
    loading: 'Üyeler yükleniyor…',
    loadErrorTitle: 'Üyeler yüklenemedi',
    empty: 'Üye yok.',
    roleLabel: 'Rol',
    youBadge: 'Bu sizsiniz',
    ownerBadge: 'Sahip',
    remove: 'Çıkar',
    removing: 'Çıkarılıyor…',
    removeConfirmTitle: 'Üye çıkarılsın mı?',
    removeConfirmDescription:
      'Bu kişi workspace’ten çıkarılacak. Tekrar erişmesi için yeniden davet edilmesi gerekir.',
    removeConfirm: 'Çıkar',
    leave: 'Workspace’ten ayrıl',
    leaving: 'Ayrılınıyor…',
    leaveConfirmTitle: 'Workspace’ten ayrılınsın mı?',
    leaveConfirmDescription:
      'Bu workspace’e erişiminizi kaybedersiniz. Tekrar erişmek için yeniden davet edilmeniz gerekir.',
    leaveConfirm: 'Ayrıl',
  },
  board: {
    listSectionTitle: 'Panolar',
    listSectionDescription: 'Bu workspace’teki panolar.',
    loading: 'Panolar yükleniyor…',
    loadErrorTitle: 'Panolar yüklenemedi',
    empty: 'Henüz pano yok — ilkini oluştur.',
    archivedBadge: 'Arşivli',
    newButton: 'Pano oluştur',
    roleBadgePrefix: 'Rol:',
    create: {
      title: 'Yeni pano',
      description: 'Bir ad verin; bu panonun yöneticisi siz olursunuz.',
      nameLabel: 'Pano adı',
      namePlaceholder: 'Örn. Ürün Yol Haritası',
      submit: 'Oluştur',
      submitting: 'Oluşturuluyor…',
    },
    settings: {
      open: 'Board ayarları',
      dialogTitle: 'Board ayarları',
      dialogDescription: 'Üyeleri, davetleri ve etiketleri yönetin.',
      membersTitle: 'Üyeler',
      membersDescription: 'Bu board’un üyelerini görüntüleyin; rollerini değiştirin veya çıkarın.',
      membersLoading: 'Üyeler yükleniyor…',
      membersLoadErrorTitle: 'Üyeler yüklenemedi',
      membersEmpty: 'Bu board’da üye yok.',
      inheritedNote: 'Workspace yöneticisi — düzenlenemez',
      roleLabel: 'Rol',
      youBadge: 'Bu sizsiniz',
      lastAdminNote: 'Tek board yöneticisi — düşürülemez/çıkarılamaz',
      remove: 'Çıkar',
      removing: 'Çıkarılıyor…',
      removeConfirmTitle: 'Üye board’dan çıkarılsın mı?',
      removeConfirmDescription:
        'Bu kişi board’dan çıkarılır. Kartlardaki atamaları/izlemeleri korunur, ama board erişimi olmadan kart işlemleri yapamaz.',
      removeConfirm: 'Çıkar',
      leave: 'Board’dan ayrıl',
      leaving: 'Ayrılınıyor…',
      leaveConfirmTitle: 'Board’dan ayrılınsın mı?',
      leaveConfirmDescription:
        'Bu board’a erişiminizi kaybedersiniz. Tekrar erişmek için yeniden eklenmeniz/davet edilmeniz gerekir.',
      leaveConfirm: 'Ayrıl',
      addTitle: 'Üye ekle',
      addDescription: 'E-posta ile board’a bir üye ekleyin veya davet gönderin.',
      addEmailLabel: 'E-posta',
      addEmailPlaceholder: 'ornek@eposta.com',
      addRoleLabel: 'Rol',
      addSubmit: 'Ekle',
      addSubmitting: 'Ekleniyor…',
      addedNotice: 'eklendi.',
      addedAsGuestNotice: 'workspace misafiri olarak eklendi.',
      invitedNotice: 'e-posta adresine davet gönderildi.',
      sentInvitationsTitle: 'Gönderilmiş davetler',
      sentInvitationsDescription: 'Bu board’a gönderilen ve henüz yanıtlanmamış davetler.',
      invitationsLoadErrorTitle: 'Davetler yüklenemedi',
      noSentInvitations: 'Bekleyen davet yok.',
      revoke: 'İptal et',
      revoking: 'İptal ediliyor…',
      revokeConfirmTitle: 'Davet iptal edilsin mi?',
      revokeConfirmDescription:
        'Bu davet geçersiz hale gelir. Kişi davet bağlantısını artık kullanamaz.',
      revokeConfirm: 'Daveti iptal et',
      invitedBy: 'Davet eden',
      expiresAt: 'Son tarih',
      labelsTitle: 'Etiketler',
      labelsDescription: 'Bu board’un etiket paletini yönetin.',
      labelsLoading: 'Etiketler yükleniyor…',
      labelsLoadErrorTitle: 'Etiketler yüklenemedi',
      labelsEmpty: 'Bu board’da etiket yok.',
      labelUnnamed: '(adsız)',
      labelNameLabel: 'Ad (isteğe bağlı)',
      labelNamePlaceholder: 'Örn. Acil',
      labelColorLabel: 'Renk',
      labelColorOf: 'Renk:',
      labelAdd: 'Etiket ekle',
      labelAdding: 'Ekleniyor…',
      labelEdit: 'Düzenle',
      labelSave: 'Kaydet',
      labelSaving: 'Kaydediliyor…',
      labelDelete: 'Sil',
      labelDeleting: 'Siliniyor…',
      labelDeleteConfirmTitle: 'Etiket silinsin mi?',
      labelDeleteConfirmDescription:
        'Bu etiket silinir ve tüm kartlardan kaldırılır. Geri alınamaz.',
      labelDeleteConfirm: 'Sil',
    },
    filter: {
      labelsTitle: 'Etikete göre filtrele',
      clearLabels: 'Temizle',
      allLabels: 'Tümü',
      unnamedLabel: '(adsız)',
      noLabels: 'Bu board’da etiket yok.',
      showArchivedLists: 'Arşivli listeleri göster',
      hideArchivedLists: 'Arşivli listeleri gizle',
      archivedListsToggle: 'Arşivli listeleri göster',
      archivedListCount: 'arşivli liste',
    },
    detail: {
      backToWorkspace: 'Workspace’e dön',
      loading: 'Pano yükleniyor…',
      loadErrorTitle: 'Pano yüklenemedi',
      archivedNote: 'Bu pano arşivli — salt okunur.',
      rename: 'Pano adını değiştir',
      renamePlaceholder: 'Pano adı',
      renameSave: 'Kaydet',
      renameSaving: 'Kaydediliyor…',
      renameCancel: 'Vazgeç',
      archive: 'Panoyu arşivle',
      archiving: 'Arşivleniyor…',
      archiveConfirmTitle: 'Pano arşivlensin mi?',
      archiveConfirmDescription:
        'Bu pano arşivlenir ve salt okunur olur. İçerik silinmez; bir yönetici geri alabilir.',
      archiveConfirm: 'Arşivle',
      restore: 'Panoyu geri yükle',
      restoring: 'Geri yükleniyor…',
      emptyBoard: 'Bu panoda henüz liste yok.',
    },
    skeleton: {
      loading: 'Pano yükleniyor…',
    },
    topBar: {
      eyebrow: 'Pano',
      archivedBadge: 'Arşivli',
      favorite: 'Favorilere ekle',
      unfavorite: 'Favorilerden çıkar',
      favoriteSoon: 'Favoriler yakında geliyor.',
      viewBoard: 'Pano',
      viewList: 'Liste',
      viewLabels: 'Etiketler',
      viewSoon: 'Bu görünüm yakında geliyor.',
      invite: 'Davet et / paylaş',
      search: 'Bu panoda ara',
      searchSoon: 'Pano içi arama yakında geliyor.',
      activity: 'Pano işlemleri',
      activitySoon: 'Pano işlemleri yakında geliyor.',
      more: 'Diğer işlemler',
      menuRename: 'Pano adını değiştir',
      menuArchive: 'Panoyu arşivle',
      menuRestore: 'Panoyu geri yükle',
      menuSettings: 'Pano ayarları',
    },
    column: {
      addList: 'Liste ekle',
      addListPlaceholder: 'Liste adı',
      addListSubmit: 'Ekle',
      addListSubmitting: 'Ekleniyor…',
      renamePlaceholder: 'Liste adı',
      renameSave: 'Kaydet',
      renameSaving: 'Kaydediliyor…',
      archive: 'Listeyi arşivle',
      archiving: 'Arşivleniyor…',
      archiveConfirmTitle: 'Liste arşivlensin mi?',
      archiveConfirmDescription:
        'Bu liste arşivlenir. İçindeki kartlar korunur; bir üye listeyi geri alabilir.',
      archiveConfirm: 'Arşivle',
      restore: 'Listeyi geri yükle',
      restoring: 'Geri yükleniyor…',
      archivedLabel: 'Arşivli',
      empty: 'Bu listede kart yok.',
      cardCount: 'kart',
      members: 'Pano üyeleri',
      more: 'Liste işlemleri',
      menuRename: 'Yeniden adlandır',
      menuArchive: 'Listeyi arşivle',
      menuRestore: 'Listeyi geri yükle',
    },
    dnd: {
      // Drag handles + the keyboard/button alternative (card ⋮ "move", column ⋮ "move left/right").
      listDragHandleLabel: 'Listeyi sürükleyerek taşı',
      move: 'Taşı',
      moveToList: 'Listeye taşı',
      moveToListEnd: 'sonuna ekle',
      moveLeft: 'Sola taşı',
      moveRight: 'Sağa taşı',
      // aria-live announcements while dragging (best-effort).
      announceCardGrabbed: 'Kart kaldırıldı. Bırakmak için fareyi taşıyın.',
      announceListGrabbed: 'Liste kaldırıldı. Bırakmak için fareyi taşıyın.',
      announceDropped: 'Bırakıldı.',
      // Low-noise feedback when a move fails / conflicts.
      error: 'Taşıma başarısız oldu. Lütfen tekrar deneyin.',
      conflict: 'Kart başkası tarafından taşındı; görünüm yenilendi.',
    },
    card: {
      addCard: 'Kart ekle',
      addCardPlaceholder: 'Kart için bir başlık girin…',
      addCardSubmit: 'Ekle',
      addCardSubmitting: 'Ekleniyor…',
      addCardCancel: 'Vazgeç',
      edit: 'Kartı düzenle',
      completeToggle: 'Kartı tamamlandı olarak işaretle',
      completeUntoggle: 'Tamamlandı işaretini kaldır',
      archive: 'Kartı arşivle',
      archiving: 'Arşivleniyor…',
      archiveConfirmTitle: 'Kart arşivlensin mi?',
      archiveConfirmDescription: 'Bu kart arşivlenir ve panodan kaldırılır.',
      archiveConfirm: 'Arşivle',
      unnamedLabel: 'Etiket',
      dueLabel: 'Son tarih',
      overdueBadge: 'Gecikti',
      dueTooltip: 'Son tarih',
      overdueTooltip: 'Süresi geçti',
      dueSoonTooltip: 'Son tarih yaklaşıyor',
      descriptionTooltip: 'Açıklama var',
      checklistTooltip: 'Yapılacaklar',
      commentsTooltip: 'Yorumlar',
      membersTooltip: 'Üyeler',
      membersMore: 'üye daha',
      open: 'Kartı aç',
      editDialogTitle: 'Kartı düzenle',
      editDialogReadonlyTitle: 'Kart',
      titleLabel: 'Başlık',
      titlePlaceholder: 'Kart başlığı',
      descriptionLabel: 'Açıklama',
      descriptionPlaceholder: 'Bu kart hakkında notlar…',
      dueAtLabel: 'Son tarih',
      noDescription: 'Açıklama yok.',
      noDueAt: 'Son tarih yok.',
      save: 'Kaydet',
      saving: 'Kaydediliyor…',
      noChange: 'Değişiklik yok.',
      close: 'Kapat',
    },
  },
  card: {
    detail: {
      loading: 'Kart yükleniyor…',
      loadErrorTitle: 'Kart yüklenemedi',
      notFound: 'Kart bulunamadı.',
      close: 'Kapat',
      archivedNote: 'Bu kart arşivli — salt okunur.',
      archive: 'Kartı arşivle',
      archiving: 'Arşivleniyor…',
      restore: 'Kartı geri yükle',
      restoring: 'Geri yükleniyor…',
      titleLabel: 'Kart başlığı',
      titleSave: 'Kaydet',
      titleSaving: 'Kaydediliyor…',
      titleCancel: 'Vazgeç',
      editTitle: 'Başlığı düzenle',
      descriptionTitle: 'Açıklama',
      descriptionPlaceholder: 'Bu kart hakkında notlar…',
      descriptionEmpty: 'Açıklama yok.',
      descriptionAdd: 'Açıklama ekle',
      descriptionSave: 'Kaydet',
      descriptionSaving: 'Kaydediliyor…',
      dueTitle: 'Son tarih',
      dueEmpty: 'Son tarih yok.',
      dueLabel: 'Son tarih',
      dueSave: 'Kaydet',
      dueSaving: 'Kaydediliyor…',
      dueClear: 'Kaldır',
      dueEdit: 'Düzenle',
      dueAdd: 'Son tarih ekle',
      descriptionEmptyPrompt: 'Açıklama ekle…',
      descriptionEditAction: 'Düzenle',
      descriptionCancelAction: 'Vazgeç',
      // Card detail modal chrome (Faz 2.7C).
      modal: {
        dialogTitle: 'Kart ayrıntıları',
        archivedBadge: 'Arşivli',
        overdueBadge: 'Gecikti',
        breadcrumbBoard: 'Pano',
        breadcrumbList: 'Liste',
        notifications: 'Bildirimler',
        notificationsSoon: 'Kart bildirimleri yakında geliyor.',
        copyLink: 'Bağlantıyı kopyala',
        linkCopied: 'Bağlantı kopyalandı',
        more: 'Diğer işlemler',
        menuMove: 'Kartı taşı',
        menuCopy: 'Kartı kopyala',
        menuArchive: 'Kartı arşivle',
        menuRestore: 'Kartı geri yükle',
        completeToggle: 'Kartı tamamlandı olarak işaretle',
        completeUntoggle: 'Tamamlandı işaretini kaldır',
        coverColor: 'Kapak rengi',
        coverColorPickerTitle: 'Kapak rengi',
        coverColorOf: 'Kapak rengi:',
        coverColorClear: 'Kaldır',
        addMeta: 'Ekle',
        membersChip: 'Üye',
        labelsChip: 'Etiket',
        dueChip: 'Son tarih',
        attachmentAdd: 'Dosya ekle',
      },
      // Rich text editor labels (passed to @pusula/ui RichTextEditor — no hardcoded copy there).
      richText: {
        bold: 'Kalın',
        italic: 'İtalik',
        strike: 'Üstü çizili',
        code: 'Kod',
        heading1: 'Başlık 1',
        heading2: 'Başlık 2',
        heading3: 'Başlık 3',
        bulletList: 'Madde işaretli liste',
        orderedList: 'Numaralı liste',
        link: 'Bağlantı',
        linkPrompt: 'Bağlantı adresi (URL):',
      },
      // Right-panel tabs + composer.
      tabs: {
        comments: 'Yorumlar',
        activity: 'Aktivite',
        attachments: 'Ekler',
        all: 'Tümü',
      },
      composer: {
        placeholder: 'Yorum yaz, @ ile etiketle…',
        submit: 'Gönder',
        submitting: 'Gönderiliyor…',
      },
      attachments: {
        empty: 'Henüz ek yok.',
      },
    },
    members: {
      title: 'Üyeler',
      empty: 'Bu kartta üye yok.',
      addAction: 'Üye ekle',
      memberLabel: 'Üye',
      roleLabel: 'Rol',
      addSubmit: 'Ekle',
      adding: 'Ekleniyor…',
      cancel: 'Vazgeç',
      remove: 'Çıkar',
      removing: 'Çıkarılıyor…',
      noBoardMembers: 'Eklenebilecek başka board üyesi yok.',
      watchSelf: 'Bu kartı izle',
      unwatchSelf: 'İzlemeyi bırak',
      watching: 'İşleniyor…',
    },
    labels: {
      title: 'Etiketler',
      empty: 'Bu kartta etiket yok.',
      addAction: 'Etiket ekle/kaldır',
      cancel: 'Kapat',
      remove: 'Kaldır',
      add: 'Ekle',
      working: 'İşleniyor…',
      unnamed: '(adsız)',
      createTitle: 'Yeni etiket',
      createColorLabel: 'Renk',
      createNameLabel: 'Ad (isteğe bağlı)',
      createNamePlaceholder: 'Örn. Acil',
      createSubmit: 'Etiket oluştur',
      creating: 'Oluşturuluyor…',
      colorOf: 'Renk:',
    },
    checklist: {
      title: 'Yapılacaklar',
      empty: 'Bu kartta yapılacak listesi yok.',
      addAction: 'Liste ekle',
      addTitlePlaceholder: 'Liste adı',
      addSubmit: 'Ekle',
      adding: 'Ekleniyor…',
      cancel: 'Vazgeç',
      rename: 'Yeniden adlandır',
      renameSave: 'Kaydet',
      renameSaving: 'Kaydediliyor…',
      renamePlaceholder: 'Liste adı',
      delete: 'Listeyi sil',
      deleting: 'Siliniyor…',
      deleteConfirmTitle: 'Liste silinsin mi?',
      deleteConfirmDescription: 'Bu yapılacaklar listesi ve içindeki maddeler silinir.',
      deleteConfirm: 'Sil',
      progress: 'maddeden',
      progressDone: 'tamamlandı',
      itemAddAction: 'Madde ekle',
      itemPlaceholder: 'Bir madde ekle…',
      itemAddSubmit: 'Ekle',
      itemAdding: 'Ekleniyor…',
      itemCancel: 'Vazgeç',
      itemEdit: 'Düzenle',
      itemSave: 'Kaydet',
      itemSaving: 'Kaydediliyor…',
      itemDelete: 'Sil',
      itemDeleting: 'Siliniyor…',
      itemToggleLabel: 'Tamamlandı olarak işaretle',
      overallProgressLabel: 'Toplam ilerleme',
      checklistProgressLabel: 'Liste ilerlemesi',
    },
    comments: {
      title: 'Yorumlar',
      empty: 'Henüz yorum yok.',
      addPlaceholder: 'Bir yorum yazın…',
      addSubmit: 'Yorum ekle',
      adding: 'Ekleniyor…',
      deletedPlaceholder: 'Bu yorum silindi.',
      editedSuffix: '(düzenlendi)',
      edit: 'Düzenle',
      editSave: 'Kaydet',
      editSaving: 'Kaydediliyor…',
      editCancel: 'Vazgeç',
      delete: 'Sil',
      deleting: 'Siliniyor…',
      deleteConfirmTitle: 'Yorum silinsin mi?',
      deleteConfirmDescription: 'Bu yorum silinir; yerine "silindi" notu görünür.',
      deleteConfirm: 'Sil',
      unknownAuthor: 'Bilinmeyen kullanıcı',
    },
    activity: {
      title: 'İşlemler',
      empty: 'Henüz aktivite yok.',
      loadErrorTitle: 'İşlemler yüklenemedi',
      unknownActor: 'Bir kullanıcı',
    },
  },
  invitations: {
    inviteAction: 'Üye davet et',
    inviteDialogTitle: 'Workspace’e üye davet et',
    inviteDialogDescription: 'Davet edilen kişiye e-posta ile davet bağlantısı gönderilir.',
    inviteEmailLabel: 'E-posta',
    inviteEmailPlaceholder: 'ornek@eposta.com',
    inviteSubmit: 'Davet gönder',
    inviteSubmitting: 'Gönderiliyor…',
    pendingTitle: 'Bekleyen davetler',
    workspaceGroupTitle: 'Workspace davetleri',
    boardGroupTitle: 'Board davetleri',
    inWorkspace: 'workspace',
    accept: 'Kabul et',
    accepting: 'Kabul ediliyor…',
    decline: 'Reddet',
    declining: 'Reddediliyor…',
    invitedBy: 'Davet eden',
    expiresAt: 'Son tarih',
    sentTitle: 'Gönderilmiş davetler',
    sentDescription: 'Bu workspace’e gönderilen ve henüz yanıtlanmamış davetler.',
    loadErrorTitle: 'Davetler yüklenemedi',
    noSent: 'Bekleyen davet yok.',
    revoke: 'İptal et',
    revoking: 'İptal ediliyor…',
    revokeConfirmTitle: 'Davet iptal edilsin mi?',
    revokeConfirmDescription:
      'Bu davet geçersiz hale gelir. Kişi davet bağlantısını artık kullanamaz.',
    revokeConfirm: 'Daveti iptal et',
  },
  onboarding: {
    title: 'Pusula’ya hoş geldin',
    intro:
      'Çalışma alanların (workspace) ekiplerini ve panolarını gruplar; her panoda listeler ve kartlarla işleri takip edersin. Başlamak için ilk çalışma alanını oluştur.',
    hint: 'Otomatik bir çalışma alanı oluşturulamadı. Aşağıdan kendin oluşturabilirsin.',
    createCta: 'İlk çalışma alanını oluştur',
  },
  account: {
    pageTitle: 'Hesap ayarları',
    pageDescription: 'Profilini, parolanı ve hesabını yönet.',
    loading: 'Hesap bilgileri yükleniyor…',
    backToWorkspaces: 'Çalışma alanlarına dön',
    profile: {
      title: 'Profil',
      description: 'Adını ve avatarını güncelle.',
      nameLabel: 'Ad',
      namePlaceholder: 'Adınız',
      imageLabel: 'Avatar bağlantısı (URL)',
      imagePlaceholder: 'https://…',
      imageHelp: 'Profil resminizin bağlantısı. Boş bırakırsanız avatar kaldırılır.',
      emailLabel: 'E-posta',
      emailReadonlyHelp: 'E-posta adresi şu an buradan değiştirilemiyor.',
      save: 'Kaydet',
      saving: 'Kaydediliyor…',
      saved: 'Profil güncellendi.',
      noChange: 'Değişiklik yok.',
    },
    password: {
      title: 'Parola',
      description: 'Hesabının parolasını değiştir.',
      currentLabel: 'Mevcut parola',
      newLabel: 'Yeni parola',
      confirmLabel: 'Yeni parola (tekrar)',
      placeholder: '••••••••',
      mismatch: 'Parolalar eşleşmiyor.',
      save: 'Parolayı değiştir',
      saving: 'Değiştiriliyor…',
      saved: 'Parolan değiştirildi. Diğer oturumların kapatıldı.',
    },
    danger: {
      title: 'Tehlikeli bölge',
      description: 'Hesabını kalıcı olarak sil. Bu işlem geri alınamaz.',
      deleteAction: 'Hesabımı sil',
      deleting: 'Siliniyor…',
      blockedOwnerTitle: 'Hesabını şu an silemezsin',
      blockedOwnerDescription:
        'Bir veya daha fazla çalışma alanının sahibisin. Hesabını silmeden önce o çalışma alanlarını sil, arşivle veya başka birine devret.',
      goToWorkspaces: 'Çalışma alanlarına git',
      dialogTitle: 'Hesabını kalıcı olarak sil',
      dialogDescription:
        'Bu işlem geri alınamaz. Hesabın, üyeliklerin ve sana ait içerik kalıcı olarak silinir. Onaylamak için parolanı gir.',
      passwordLabel: 'Parola',
      passwordPlaceholder: '••••••••',
      confirm: 'Hesabımı kalıcı sil',
    },
  },
} as const;
